"use strict";

/* NEXUS Global Alpha v2.0.0 · Strategic Command
   Catálogo de plataformas reales, fotografías reutilizables, planeamiento
   operacional y lectura estratégica global. Las cifras siguen siendo simuladas.
*/
(() => {
  const E=window.NEXUS_ECONOMY;
  if(!E)throw new Error("alpha-v20.js requiere NEXUS_ECONOMY.");
  const oldCreate=E.createInitialState,oldHydrate=E.hydrateState,oldTick=E.tickDay,oldQueue=E.queueUnitBatch,oldLaunch=E.launchWarCampaign,oldMobilize=E.mobilizeReserves;
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)||0));
  const round=(v,d=1)=>Number((Number(v)||0).toFixed(d));

  const PHOTOS={
    infantry:"assets/military/infantry.jpg",mechanized:"assets/military/mechanized.jpg",armor:"assets/military/armor.jpg",
    artillery:"assets/military/artillery.jpg",airDefense:"assets/military/air-defense.jpg",rocketArtillery:"assets/military/artillery.jpg",
    fighter:"assets/military/fighter.jpg",drone:"assets/military/drone.jpg",bomber:"assets/military/bomber.jpg",transport:"assets/military/transport.jpg",
    frigate:"assets/military/destroyer.jpg",destroyer:"assets/military/destroyer.jpg",submarine:"assets/military/submarine.jpg",carrier:"assets/military/carrier.jpg",
    satellite:"assets/military/satellite.jpg",missile:"assets/military/air-defense.jpg",cyber:"assets/military/cyber.jpg"
  };
  const p=(name,manufacturer,generation,role)=>({name,manufacturer,generation,role});
  const EXPORT_PLATFORMS={
    infantry:[p("Brigada de infantería modular","Industria nacional","4ª gen.","Control territorial y combate urbano")],
    mechanized:[p("M2A4 Bradley","BAE Systems / GDLS","4ª gen.","Infantería mecanizada y reconocimiento")],
    armor:[p("Leopard 2A7","Krauss-Maffei Wegmann","4ª gen.","Ruptura acorazada y combate de alta intensidad")],
    artillery:[p("M109A7 Paladin","BAE Systems","4ª gen.","Fuegos de apoyo de 155 mm")],
    airDefense:[p("MIM-104 Patriot PAC-3","Raytheon / Lockheed Martin","4ª gen.","Defensa aérea y antimisil")],
    rocketArtillery:[p("M142 HIMARS","Lockheed Martin","4ª gen.","Fuegos de precisión de largo alcance")],
    fighter:[p("F-35A Lightning II","Lockheed Martin","5ª gen.","Caza de ataque furtivo multirrol"),p("F-16V Block 70","Lockheed Martin","4.5ª gen.","Caza multirrol")],
    drone:[p("MQ-9B SkyGuardian","General Atomics","4ª gen.","ISR persistente y ataque de precisión")],
    bomber:[p("B-2A Spirit","Northrop Grumman","5ª gen.","Ataque estratégico furtivo")],
    transport:[p("C-17A Globemaster III","Boeing","4ª gen.","Transporte estratégico y aerotransporte")],
    frigate:[p("FREMM clase Bergamini","Fincantieri / Naval Group","4ª gen.","Escolta oceánica y guerra antisubmarina")],
    destroyer:[p("Arleigh Burke Flight III","HII / Bath Iron Works","4ª gen.","Defensa aérea de flota y ataque naval")],
    submarine:[p("Virginia Block V","General Dynamics Electric Boat","4ª gen.","Ataque submarino y misiles de crucero")],
    carrier:[p("Gerald R. Ford CVN-78","Huntington Ingalls Industries","5ª gen.","Proyección aeronaval global")],
    satellite:[p("GPS III / plataforma ISR","Lockheed Martin","4ª gen.","Navegación, alerta e inteligencia orbital")],
    missile:[p("PrSM Increment 2","Lockheed Martin","4ª gen.","Ataque terrestre de precisión")],
    cyber:[p("Mando conjunto de ciberoperaciones","Capacidad soberana","5ª gen.","Defensa de redes y operaciones ofensivas")]
  };
  const NATIONAL={
    ESP:{
      infantry:[p("Brigada «Rey Alfonso XIII» II de La Legión","Ejército de Tierra","4ª gen.","Fuerza expedicionaria ligera")],mechanized:[p("ASCOD Pizarro Fase II","GDELS Santa Bárbara Sistemas","4ª gen.","Combate mecanizado")],armor:[p("Leopard 2E","GDELS / KMW","4ª gen.","Carro de combate principal")],artillery:[p("SIAC 155/52","GDELS Santa Bárbara Sistemas","4ª gen.","Artillería remolcada de largo alcance")],airDefense:[p("NASAMS III","Kongsberg / Raytheon","4ª gen.","Defensa aérea en red")],rocketArtillery:[p("SILAM / PULS","Escribano / Elbit Systems","4ª gen.","Artillería cohete de largo alcance")],fighter:[p("Eurofighter Typhoon Tranche 4","Airbus / Eurofighter GmbH","4.5ª gen.","Superioridad aérea y ataque"),p("EF-18M Hornet","Boeing","4ª gen.","Caza de ataque multirrol")],drone:[p("MQ-9B Predator B","General Atomics","4ª gen.","ISR y ataque persistente")],bomber:[p("Eurofighter Typhoon ECR","Airbus / Eurofighter GmbH","4.5ª gen.","Ataque profundo y guerra electrónica")],transport:[p("Airbus A400M Atlas","Airbus Defence and Space","4ª gen.","Transporte estratégico y táctico")],frigate:[p("F-110 clase Bonifaz","Navantia","4ª gen.","Escolta antisubmarina y multimisión")],destroyer:[p("F-100 Álvaro de Bazán","Navantia","4ª gen.","Defensa aérea de flota AEGIS")],submarine:[p("S-80 Plus clase Isaac Peral","Navantia","4ª gen.","Submarino oceánico AIP")],carrier:[p("LHD Juan Carlos I","Navantia","4ª gen.","Proyección anfibia y ala embarcada")],satellite:[p("Spainsat NG I/II","Hisdesat / Airbus","4ª gen.","Comunicaciones militares seguras")],missile:[p("NSM Coastal Defence System","Kongsberg","4ª gen.","Defensa litoral antibuque")],cyber:[p("Mando Conjunto del Ciberespacio","EMAD","5ª gen.","Operaciones militares en el ciberespacio")]},
    USA:{fighter:[p("F-35A Lightning II","Lockheed Martin","5ª gen.","Caza de ataque furtivo multirrol"),p("F-22A Raptor","Lockheed Martin / Boeing","5ª gen.","Superioridad aérea furtiva"),p("F-16V Block 70","Lockheed Martin","4.5ª gen.","Caza multirrol")],armor:[p("M1A2 SEPv3 Abrams","General Dynamics Land Systems","4ª gen.","Carro de combate principal")],mechanized:[p("M2A4 Bradley","BAE Systems","4ª gen.","Combate mecanizado")],artillery:[p("M109A7 Paladin","BAE Systems","4ª gen.","Artillería autopropulsada de 155 mm")],airDefense:[p("MIM-104 Patriot PAC-3 MSE","Raytheon / Lockheed Martin","4ª gen.","Defensa aérea y antimisil")],rocketArtillery:[p("M142 HIMARS","Lockheed Martin","4ª gen.","Fuegos de precisión")],drone:[p("MQ-9A Reaper","General Atomics","4ª gen.","ISR y ataque persistente")],bomber:[p("B-21 Raider","Northrop Grumman","6ª gen.","Ataque estratégico furtivo"),p("B-2A Spirit","Northrop Grumman","5ª gen.","Ataque estratégico furtivo")],transport:[p("C-17A Globemaster III","Boeing","4ª gen.","Movilidad aérea global")],destroyer:[p("Arleigh Burke Flight III","HII / Bath Iron Works","4ª gen.","Defensa aérea y ataque naval")],frigate:[p("Constellation FFG-62","Fincantieri Marinette Marine","4ª gen.","Escolta oceánica multimisión")],submarine:[p("Virginia Block V","General Dynamics Electric Boat","4ª gen.","Ataque submarino")],carrier:[p("Gerald R. Ford CVN-78","Huntington Ingalls Industries","5ª gen.","Proyección aeronaval global")],missile:[p("PrSM Increment 2","Lockheed Martin","4ª gen.","Ataque terrestre de precisión")],cyber:[p("US Cyber Command Mission Force","USCYBERCOM","5ª gen.","Operaciones cibernéticas conjuntas")]},
    FRA:{fighter:[p("Rafale F4","Dassault Aviation","4.5ª gen.","Caza omnirol")],armor:[p("Leclerc XLR","Nexter","4ª gen.","Carro de combate principal")],artillery:[p("CAESAR 8x8","Nexter","4ª gen.","Artillería autopropulsada de 155 mm")],frigate:[p("FREMM Aquitaine","Naval Group","4ª gen.","Escolta multimisión")],submarine:[p("Suffren clase Barracuda","Naval Group","4ª gen.","Submarino nuclear de ataque")],carrier:[p("Charles de Gaulle R91","Naval Group","4ª gen.","Proyección aeronaval nuclear")]},
    GBR:{fighter:[p("F-35B Lightning II","Lockheed Martin","5ª gen.","Caza embarcado STOVL"),p("Eurofighter Typhoon FGR4","BAE Systems / Eurofighter","4.5ª gen.","Superioridad aérea")],armor:[p("Challenger 3","Rheinmetall BAE Systems Land","4ª gen.","Carro de combate principal")],destroyer:[p("Type 45 clase Daring","BAE Systems Maritime","4ª gen.","Defensa aérea de flota")],frigate:[p("Type 26 clase City","BAE Systems Maritime","4ª gen.","Guerra antisubmarina")],submarine:[p("Astute class","BAE Systems Submarines","4ª gen.","Submarino nuclear de ataque")],carrier:[p("Queen Elizabeth class","Aircraft Carrier Alliance","5ª gen.","Proyección aeronaval STOVL")]},
    DEU:{fighter:[p("Eurofighter Typhoon Tranche 4","Airbus / Eurofighter GmbH","4.5ª gen.","Superioridad aérea multirrol")],armor:[p("Leopard 2A7V","KMW / Rheinmetall","4ª gen.","Carro de combate principal")],mechanized:[p("Puma IFV","PSM","4ª gen.","Combate mecanizado")],artillery:[p("PzH 2000","KMW / Rheinmetall","4ª gen.","Artillería autopropulsada")],frigate:[p("F126 clase Niedersachsen","Damen / Blohm+Voss","4ª gen.","Fragata multimisión")],submarine:[p("Type 212A","TKMS","4ª gen.","Submarino AIP") ]},
    CHN:{fighter:[p("Chengdu J-20A Mighty Dragon","Chengdu Aerospace","5ª gen.","Superioridad aérea furtiva"),p("Shenyang J-16D","Shenyang Aircraft","4.5ª gen.","Ataque y guerra electrónica")],armor:[p("ZTZ-99A","Norinco","4ª gen.","Carro de combate principal")],mechanized:[p("ZBD-04A","Norinco","4ª gen.","Combate mecanizado")],rocketArtillery:[p("PHL-16","Norinco","4ª gen.","Fuegos de largo alcance")],destroyer:[p("Type 055 Renhai","Dalian / Jiangnan Shipyard","4ª gen.","Defensa aérea y ataque naval")],frigate:[p("Type 054B","Hudong-Zhonghua","4ª gen.","Escolta multimisión")],submarine:[p("Type 093B Shang III","Bohai Shipyard","4ª gen.","Submarino nuclear de ataque")],carrier:[p("Fujian Type 003","Jiangnan Shipyard","5ª gen.","Proyección aeronaval CATOBAR")],missile:[p("DF-26","CASIC","4ª gen.","Misil balístico de alcance intermedio")]},
    RUS:{fighter:[p("Sukhoi Su-57 Felon","United Aircraft Corporation","5ª gen.","Caza furtivo multirrol"),p("Sukhoi Su-35S","United Aircraft Corporation","4.5ª gen.","Superioridad aérea")],armor:[p("T-90M Proryv","Uralvagonzavod","4ª gen.","Carro de combate principal")],mechanized:[p("BMP-3M","Kurganmashzavod","4ª gen.","Combate mecanizado")],artillery:[p("2S19M2 Msta-S","Uraltransmash","4ª gen.","Artillería autopropulsada")],airDefense:[p("S-400 Triumf","Almaz-Antey","4ª gen.","Defensa aérea de largo alcance")],rocketArtillery:[p("9A54 Tornado-S","Splav","4ª gen.","Artillería cohete de precisión")],destroyer:[p("Proyecto 22350 Admiral Gorshkov","Severnaya Verf","4ª gen.","Escolta y ataque naval")],submarine:[p("Yasen-M","Sevmash","4ª gen.","Submarino nuclear de ataque")],missile:[p("9K720 Iskander-M","KB Mashinostroyeniya","4ª gen.","Misil balístico táctico")]},
    IND:{fighter:[p("Rafale EH","Dassault Aviation","4.5ª gen.","Caza omnirol"),p("Su-30MKI","HAL / Sukhoi","4.5ª gen.","Superioridad aérea multirrol")],armor:[p("T-90S Bhishma","HVF / Uralvagonzavod","4ª gen.","Carro de combate principal")],artillery:[p("K9 Vajra-T","Larsen & Toubro / Hanwha","4ª gen.","Artillería autopropulsada")],destroyer:[p("Visakhapatnam class","Mazagon Dock Shipbuilders","4ª gen.","Destructor furtivo lanzamisiles")],submarine:[p("Kalvari class","Mazagon Dock / Naval Group","4ª gen.","Submarino convencional")],carrier:[p("INS Vikrant R11","Cochin Shipyard","4ª gen.","Proyección aeronaval STOBAR")],missile:[p("BrahMos Block III","BrahMos Aerospace","4ª gen.","Misil de crucero supersónico")]},
    JPN:{fighter:[p("F-35A Lightning II","Mitsubishi / Lockheed Martin","5ª gen.","Caza de ataque furtivo")],armor:[p("Type 10","Mitsubishi Heavy Industries","4ª gen.","Carro de combate principal")],destroyer:[p("Maya class","Japan Marine United","4ª gen.","Defensa aérea AEGIS")],submarine:[p("Taigei class","Mitsubishi / Kawasaki","4ª gen.","Submarino oceánico")],carrier:[p("Izumo class F-35B conversion","Japan Marine United","5ª gen.","Proyección aeronaval STOVL")]},
    ISR:{fighter:[p("F-35I Adir","Lockheed Martin / IAI","5ª gen.","Caza de ataque furtivo")],armor:[p("Merkava Mk.4 Barak","Mantak","4ª gen.","Carro de combate principal")],airDefense:[p("Arrow 3 / David's Sling","IAI / Rafael","4ª gen.","Defensa aérea multicapa")],drone:[p("IAI Heron TP","Israel Aerospace Industries","4ª gen.","ISR y ataque persistente")],missile:[p("LORA","Israel Aerospace Industries","4ª gen.","Ataque terrestre de precisión")]}
  };

  const EXTRA_CAMPAIGNS=[
    {id:"isrRecon",icon:"🛰️",name:"Reconocimiento ISR conjunto",domain:"Espacio / aire / ciber",days:3,cost:1.1,capital:2,fuel:1,munitions:0,requires:["drone","satellite"],description:"Satélites, drones y guerra electrónica construyen el cuadro de situación enemigo.",effect:"Eleva la inteligencia y reduce la incertidumbre de las campañas posteriores.",prerequisite:"Sin requisito"},
    {id:"sead",icon:"📡",name:"Supresión de defensas aéreas",domain:"Aire",days:5,cost:2.9,capital:5,fuel:5,munitions:7,requires:["fighter","missile"],description:"Ataques coordinados contra radares, SAM y nodos de mando.",effect:"Abre corredores aéreos y degrada la defensa antiaérea.",prerequisite:"ISR completado o superioridad aérea ≥45"},
    {id:"antiSubmarine",icon:"🌐",name:"Campaña antisubmarina",domain:"Mar / aire",days:7,cost:2.5,capital:4,fuel:6,munitions:3,requires:["frigate","destroyer"],description:"Patrullas, sonares, helicópteros y barreras marítimas contra submarinos.",effect:"Aumenta el control naval y protege los corredores logísticos.",prerequisite:"Capacidad de escolta oceánica"},
    {id:"navalStrike",icon:"🚀",name:"Ataque naval de largo alcance",domain:"Mar / aire",days:5,cost:3.8,capital:6,fuel:6,munitions:9,requires:["fighter","destroyer","missile"],description:"Misiles antibuque y aviación naval atacan grupos de superficie y puertos.",effect:"Degrada el control naval, los puertos y el suministro enemigo.",prerequisite:"ISR completado"},
    {id:"airborneAssault",icon:"🪂",name:"Asalto aerotransportado",domain:"Aire / tierra",days:6,cost:4.2,capital:8,fuel:8,munitions:7,requires:["transport","infantry"],description:"Fuerzas aerotransportadas toman aeródromos, puentes y centros de mando.",effect:"Puede abrir una cabeza de puente antes de la invasión terrestre.",prerequisite:"Superioridad aérea ≥58"},
    {id:"specialForcesRaid",icon:"🥷",name:"Incursión de fuerzas especiales",domain:"Especial / ciber",days:4,cost:1.7,capital:4,fuel:2,munitions:3,requires:["infantry","drone","cyber"],description:"Equipos especiales atacan objetivos críticos con apoyo ISR y cibernético.",effect:"Reduce logística e inteligencia con riesgo político limitado.",prerequisite:"ISR completado"}
  ];
  const PLAN_OPTIONS={tempo:["deliberate","balanced","surge"],roe:["discriminate","standard","unrestricted"],priority:["forces","logistics","infrastructure"]};

  function country(state,id=state.controlledCountryId){return state.countries.find(c=>c.id===id)}
  function modelsFor(c,type){return NATIONAL[c?.id]?.[type]||EXPORT_PLATFORMS[type]||[]}
  function nextMilitaryPlatform(state,c,type){const lines=modelsFor(c,type),count=(c.units||[]).filter(u=>u.typeId===type).length+(c.productionQueue||[]).filter(q=>q.kind==="unitV2"&&q.typeId===type).length;return lines[count%Math.max(1,lines.length)]||p(type,"Industria nacional","4ª gen.","Capacidad militar")}
  function platformId(c,type,model){return `${c.id}-${type}-${String(model.name).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}`}
  function assignUnitPlatform(state,c,u,index=0){
    const lines=modelsFor(c,u.typeId),model=u.modelName?{name:u.modelName,manufacturer:u.manufacturer,generation:u.generation,role:u.role}:lines[index%Math.max(1,lines.length)]||nextMilitaryPlatform(state,c,u.typeId);
    u.modelId||=platformId(c,u.typeId,model);u.modelName||=model.name;u.manufacturer||=model.manufacturer;u.generation||=model.generation;u.role||=model.role;u.photo=PHOTOS[u.typeId]||u.photo;
    u.formationName||=u.displayName||u.name||`${c.flag} Grupo ${String(index+1).padStart(2,"0")}`;
    if(!u.formationName.startsWith(model.name))u.displayName=`${model.name} · ${u.formationName}`;
    else u.displayName=u.formationName;
    u.name=u.displayName;return u;
  }
  function ensurePlatforms(state){
    for(const def of state.unitCatalog||[]){def.symbolIcon||=def.icon;def.photo=PHOTOS[def.id]||def.photo;def.icon=def.photo||def.icon;def.platformFamily=true}
    for(const c of state.countries||[]){const counters={};for(const u of c.units||[]){const i=counters[u.typeId]||0;assignUnitPlatform(state,c,u,i);counters[u.typeId]=i+1}for(const q of c.productionQueue||[]){if(q.kind!=="unitV2")continue;const model=q.modelName?{name:q.modelName,manufacturer:q.manufacturer,generation:q.generation,role:q.role}:nextMilitaryPlatform(state,c,q.typeId);q.modelId||=platformId(c,q.typeId,model);q.modelName||=model.name;q.manufacturer||=model.manufacturer;q.generation||=model.generation;q.role||=model.role;q.name=q.modelName;q.photo=PHOTOS[q.typeId]}}
  }
  function ensureCampaigns(){for(const def of EXTRA_CAMPAIGNS)if(!(E.campaignDefinitions||[]).some(x=>x.id===def.id))E.campaignDefinitions.push(def);const prereq={precisionStrike:"Superioridad aérea ≥45",amphibiousAssault:"Control naval ≥58 y superioridad aérea ≥45",landInvasion:"Logística de campaña ≥40",totalWar:"Movilización y control multidominio"};for(const d of E.campaignDefinitions||[])d.prerequisite||=prereq[d.id]||"Capacidad militar disponible"}
  function ensurePlans(state){for(const w of state.wars||[]){w.operationalPlan||={};for(const side of ["attacker","defender"])w.operationalPlan[side]||={tempo:"balanced",roe:"discriminate",priority:"forces",support:50,updated:state.date};w.intelligencePicture||={attacker:28,defender:28};w.supplyState||={attacker:62,defender:62}}}
  function ensureV20(state){state.version="2.0.0-alpha";state.settings||={};state.settings.professionalUI??=true;state.settings.mapAnimations??=true;ensureCampaigns();ensurePlatforms(state);ensurePlans(state);return state}

  function queueUnitBatch(state,typeId,regionId,quantity=1){const c=country(state),model=nextMilitaryPlatform(state,c,typeId),result=oldQueue(state,typeId,regionId,quantity);if(!result?.ok)return result;const q=[...(c.productionQueue||[])].reverse().find(x=>x.kind==="unitV2"&&x.typeId===typeId&&!x.modelId);if(q){q.modelId=platformId(c,typeId,model);q.modelName=model.name;q.manufacturer=model.manufacturer;q.generation=model.generation;q.role=model.role;q.photo=PHOTOS[typeId];q.name=model.name}result.message=`Contrato firmado: ${quantity.toLocaleString("es-ES")} × ${model.name}. ${result.message}`;return result}
  function completed(state,w,side,type){return (w.campaigns||[]).some(x=>x.side===side&&x.typeId===type&&x.status==="completed")}
  function campaignPrerequisite(state,w,side,type){const air=w.airSuperiority?.[side]||0,naval=w.navalControl?.[side]||0,supply=w.supplyState?.[side]||50,plan=w.operationalPlan?.[side];if(type==="sead"&&!completed(state,w,side,"isrRecon")&&air<45)return"Completa ISR o alcanza 45 de superioridad aérea.";if(["navalStrike","specialForcesRaid"].includes(type)&&!completed(state,w,side,"isrRecon"))return"Completa primero Reconocimiento ISR conjunto.";if(type==="airborneAssault"&&air<58)return"Se requiere superioridad aérea 58 o superior.";if(type==="amphibiousAssault"&&(naval<58||air<45))return"Se requiere control naval 58 y superioridad aérea 45.";if(type==="landInvasion"&&supply<40)return"El estado de suministro debe alcanzar 40.";if(type==="totalWar"&&(!plan?.mobilized||air<45||supply<55))return"Requiere reservas movilizadas, superioridad aérea 45 y suministro 55.";return null}
  function launchWarCampaign(state,warId,typeId,targetRegionId){ensurePlans(state);const w=(state.wars||[]).find(x=>x.id===warId&&!x.ended),c=country(state),side=w&&(w.attacker===c.id?"attacker":w.defender===c.id?"defender":null);if(!w||!side)return{ok:false,message:"No participas en esta guerra."};const blocked=campaignPrerequisite(state,w,side,typeId);if(blocked)return{ok:false,message:`Operación bloqueada: ${blocked}`};const result=oldLaunch(state,warId,typeId,targetRegionId);if(result?.ok){const op=w.campaigns.find(x=>x.id===result.campaignId),plan=w.operationalPlan[side];if(op){op.tempo=plan.tempo;op.roe=plan.roe;op.priority=plan.priority;op.support=plan.support;op.prerequisiteChecked=true}}return result}
  function setOperationalPlan(state,warId,tempo,roe,priority,support=50){ensurePlans(state);const w=(state.wars||[]).find(x=>x.id===warId&&!x.ended),c=country(state),side=w&&(w.attacker===c.id?"attacker":w.defender===c.id?"defender":null);if(!w||!side)return{ok:false,message:"Guerra no disponible."};if(!PLAN_OPTIONS.tempo.includes(tempo)||!PLAN_OPTIONS.roe.includes(roe)||!PLAN_OPTIONS.priority.includes(priority))return{ok:false,message:"Plan operacional inválido."};w.operationalPlan[side]={...w.operationalPlan[side],tempo,roe,priority,support:clamp(support,20,100),updated:state.date};w.operations.unshift({date:state.date,type:"operational-plan",text:`${c.name} adopta tempo ${tempo}, ROE ${roe}, prioridad ${priority} y apoyo ${clamp(support,20,100)}%.`});return{ok:true,message:"Plan operacional actualizado. Afectará consumo, impacto, bajas y legitimidad."}}
  function mobilizeReserves(state,warId){const result=oldMobilize(state,warId);if(!result?.ok)return result;const w=(state.wars||[]).find(x=>x.id===warId&&!x.ended),c=country(state),side=w&&(w.attacker===c.id?"attacker":w.defender===c.id?"defender":null);if(side){ensurePlans(state);w.operationalPlan[side].mobilized=true;w.operationalPlan[side].mobilizedDate=state.date}return{...result,message:`${result.message} La movilización habilita operaciones de guerra total si se cumplen los requisitos multidominio.`}}
  function applyV20Results(state){for(const w of state.wars||[])for(const op of w.campaigns||[]){if(op.status!=="completed"||op.v20Applied)continue;op.v20Applied=true;const side=op.side,enemySide=side==="attacker"?"defender":"attacker",enemy=country(state,op.targetCountryId),region=E.getRegion?.(state,op.targetCountryId,op.targetRegionId),plan=w.operationalPlan?.[side]||{},tempo=plan.tempo==="surge"?1.18:plan.tempo==="deliberate"?.9:1;op.impact=round((op.impact||20)*tempo,1);if(op.typeId==="isrRecon")w.intelligencePicture[side]=clamp(w.intelligencePicture[side]+op.impact*.7,0,100);if(op.typeId==="sead"){w.airSuperiority[side]=clamp((w.airSuperiority[side]||50)+op.impact*.35,0,100);for(const u of enemy?.units||[])if(u.typeId==="airDefense")u.readiness=clamp(u.readiness-op.impact*.22,0,100)}if(op.typeId==="antiSubmarine")w.navalControl[side]=clamp((w.navalControl[side]||50)+op.impact*.32,0,100);if(op.typeId==="navalStrike"){w.navalControl[enemySide]=clamp((w.navalControl[enemySide]||50)-op.impact*.28,0,100);if(region)region.infra=clamp(region.infra-op.impact*.05,0,100)}if(op.typeId==="airborneAssault"&&region&&op.impact>26){region.controllerId=side==="attacker"?w.attacker:w.defender;w.occupiedRegions||=[];if(!w.occupiedRegions.includes(region.id))w.occupiedRegions.push(region.id)}if(op.typeId==="specialForcesRaid"&&enemy){enemy.systems.logistics=clamp(enemy.systems.logistics-op.impact*.06,0,100);enemy.systems.intelligence=clamp(enemy.systems.intelligence-op.impact*.05,0,100)}const risk=plan.roe==="unrestricted"?1.8:plan.roe==="standard"?1:.45;w.civilianRisk=clamp((w.civilianRisk||10)+op.impact*.025*risk,0,100);op.civilianRisk=round(op.impact*.04*risk,1)}}
  function processPlans(state){for(const w of state.wars||[]){if(w.ended)continue;for(const side of ["attacker","defender"]){const c=country(state,side==="attacker"?w.attacker:w.defender),plan=w.operationalPlan?.[side];if(!c||!plan)continue;const active=(w.campaigns||[]).filter(x=>x.side===side&&x.status==="active").length,tempo=plan.tempo==="surge"?1.45:plan.tempo==="deliberate"?.65:1;c.strategicStockpile.fuel=round(clamp((c.strategicStockpile.fuel||0)-active*.035*tempo,0,100),2);c.strategicStockpile.munitions=round(clamp((c.strategicStockpile.munitions||0)-active*.04*tempo,0,100),2);w.supplyState[side]=round(clamp((c.systems.logistics*.55+c.strategicStockpile.fuel*.25+c.strategicStockpile.munitions*.2)-active*2.4*tempo,0,100),1);if(plan.roe==="unrestricted"){c.government.legitimacy=round(clamp(c.government.legitimacy-.015,0,100),2);c.relations&&Object.keys(c.relations).forEach(id=>c.relations[id]=round(clamp(c.relations[id]-.002,0,100),2))}}}}
  function defensePosture(state,c=country(state)){const units=c?.units||[],domain=types=>clamp(units.filter(u=>types.includes(u.typeId)).reduce((s,u)=>s+Math.sqrt(Math.max(1,u.quantity))*(u.readiness||0)/10,0),0,100),maintenance=clamp((c.militaryReadiness||0)*.55+(c.systems.industry||0)*.25+(c.systems.logistics||0)*.2,0,100);return{land:round(domain(["infantry","mechanized","armor","artillery","rocketArtillery"])),air:round(domain(["fighter","bomber","drone","airDefense"])),naval:round(domain(["frigate","destroyer","submarine","carrier"])),space:round(domain(["satellite","missile","cyber"])),maintenance:round(maintenance),supply:round((c.strategicStockpile.fuel+c.strategicStockpile.munitions)/2),command:round((c.systems.intelligence+c.systems.technology+c.militaryReadiness)/3),mobilization:round((c.militaryReadiness+c.politics.politicalCapital)/2)}}
  function globalSituation(state){const flashpoints=[];for(const w of state.wars||[]){if(w.ended)continue;flashpoints.push({type:"war",severity:clamp((w.intensity||40)+(w.civilianRisk||0)*.25,0,100),title:`${country(state,w.attacker)?.name||w.attacker} — ${country(state,w.defender)?.name||w.defender}`,detail:`Día ${w.days||0} · intensidad ${round(w.intensity||0)} · war score ${round(w.warScore||0)}`})}for(const c of state.countries||[]){if(c.sovereign===false)continue;const risk=clamp((100-c.systems.stability)*.45+(100-c.government.legitimacy)*.2+(c.warExhaustion||0)*.35,0,100);if(risk>42)flashpoints.push({type:"instability",severity:round(risk),title:`${c.flag} ${c.name}`,detail:`Estabilidad ${round(c.systems.stability)} · legitimidad ${round(c.government.legitimacy)} · agotamiento ${round(c.warExhaustion||0)}`})}return{tension:round(state.world?.tension||0),wars:(state.wars||[]).filter(w=>!w.ended).length,flashpoints:flashpoints.sort((a,b)=>b.severity-a.severity).slice(0,8),chokepoints:[{name:"Estrecho de Ormuz",risk:clamp((state.world?.tension||30)*.82,15,92)},{name:"Bab el-Mandeb",risk:clamp((state.world?.tension||30)*.76,18,90)},{name:"Canal de Suez",risk:clamp((state.world?.tension||30)*.61,12,82)},{name:"Estrecho de Malaca",risk:clamp((state.world?.tension||30)*.55,10,78)},{name:"Mar de China Meridional",risk:clamp((state.world?.tension||30)*.9,20,96)}]}}

  function tickDay(state){const summary=oldTick(state);ensureV20(state);applyV20Results(state);processPlans(state);return summary}
  function createInitialState(){const state=ensureV20(oldCreate());E.pushEvent?.(state,"system","NEXUS Global Alpha v2.0.0 · Strategic Command","Cartografía mundial reforzada, fotografías militares, plataformas nacionales reales y planeamiento operacional avanzado activados.");return state}
  function hydrateV20(state){return ensureV20(oldHydrate(state))}
  Object.assign(E,{createInitialState,hydrateState:hydrateV20,tickDay,queueUnitBatch,launchWarCampaign,setOperationalPlan,mobilizeReserves,nextMilitaryPlatform,defensePosture,globalSituation,militaryPhotoPaths:PHOTOS,nationalMilitaryPlatforms:NATIONAL,version20:true});
})();
