const esc=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);
const badge=(label,value)=>`<div class="kpi"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`;

export function renderArchitecturePanel(state,architecture){
  const systems=architecture.scheduler.manifest(),audit=(state.v54?.audit||[]).slice(-12).reverse(),events=(state.v54?.typedEvents||[]).slice(-8).reverse(),migrations=state.v54?.migrations||[],frequencies={};
  for(const system of systems)frequencies[system.frequency]=(frequencies[system.frequency]||0)+1;
  return `<div class="section-heading"><div><span class="eyebrow">NÚCLEO TÉCNICO v5.4.1</span><h2>Arquitectura modular verificable</h2><p>Un propietario por ruta, contratos tipados y simulación desacoplada del navegador.</p></div><span class="tag positive">SCHEMA ${esc(state.v54?.schema)}</span></div>
    <div class="kpi-grid">${badge("Sistemas",systems.length)}${badge("Propietarios",Object.keys(state.v54?.owners||{}).length)}${badge("Eventos tipados",state.v54?.typedEvents?.length||0)}${badge("Auditoría",state.v54?.audit?.length||0)}${badge("Worker",state.v54?.worker?.enabled?"ACTIVO":"FALLBACK DETERMINISTA")}${badge("Migraciones",migrations.length)}</div>
    <div class="dashboard-grid">
      <section class="card span-2"><div class="card-title"><h3>Planificador temporal</h3><span>${Object.entries(frequencies).map(([key,value])=>`${esc(key)} ${value}`).join(" · ")}</span></div><div class="table-wrap"><table><thead><tr><th>Sistema</th><th>Propietario</th><th>Frecuencia</th><th>Última ejecución</th></tr></thead><tbody>${systems.map(system=>{const domain=system.id.replace("simulation.",""),last=state.v54?.domains?.[domain];return`<tr><td>${esc(domain)}</td><td><code>${esc(system.owner)}</code></td><td>${esc(system.frequency)}</td><td>${last?`día ${esc(last.lastRunDay)} · ${esc(last.status)}`:"pendiente"}</td></tr>`}).join("")}</tbody></table></div></section>
      <section class="card"><div class="card-title"><h3>Garantías activas</h3><span>runtime</span></div><div class="info-list"><div><span>Bundle heredado</span><b>Congelado v5.2</b></div><div><span>Semilla</span><b>Reproducible</b></div><div><span>Guardado</span><b>Checksum + schema</b></div><div><span>Headless</span><b>Disponible</b></div><div><span>Datos</span><b>JSON externo</b></div><div><span>UI</span><b>Adaptador desacoplado</b></div></div></section>
      <section class="card span-2"><div class="card-title"><h3>Registro de auditoría</h3><span>Últimas ${audit.length} transacciones</span></div><div class="table-wrap"><table><thead><tr><th>#</th><th>Día</th><th>Propietario</th><th>Operación</th><th>Estado</th></tr></thead><tbody>${audit.map(item=>`<tr><td>${esc(item.sequence)}</td><td>${esc(item.day)}</td><td><code>${esc(item.owner)}</code></td><td>${esc(item.type)}</td><td class="${item.ok?"positive":"negative"}">${item.ok?"OK":"ERROR"}</td></tr>`).join("")||`<tr><td colspan="5">Avanza un día para registrar transacciones.</td></tr>`}</tbody></table></div></section>
      <section class="card"><div class="card-title"><h3>Flujo de eventos</h3><span>Tipado</span></div>${events.map(item=>`<div class="event-row"><div><b>${esc(item.type)}</b><small>día ${esc(item.payload?.day??"—")}</small></div></div>`).join("")||"<p>Sin eventos todavía.</p>"}</section>
    </div>`;
}
