"use strict";

(()=>{
  const X=window.NEXUS_V52,E=window.NEXUS_ECONOMY,V=window.NEXUS_V5;
  if(!X||!E)throw new Error("v5.2 requiere v5.1");
  if(E.version52)return;
  const legacy={create:E.createInitialState,hydrate:E.hydrateState,tick:E.tickDay,annex:E.annexCountry};
  const ok=message=>({ok:true,message}),fail=message=>({ok:false,message});
  const country=(s,id=s.controlledCountryId)=>E.getCountry(s,id);
  const migrate=s=>s.v52?.schema===X.SCHEMA?(s.version=X.VERSION,s):X.ensureWorld(s);
  function createInitialState(){const s=migrate(legacy.create());E.pushEvent?.(s,"system","Strategic Command v5.2 · Capacidad y conocimiento","Mando operacional, ocupación, niebla de guerra, innovación, clima y análisis estratégico activados.");return s}
  function hydrateState(s){return migrate(legacy.hydrate(s))}
  function tickDay(s){migrate(s);const result=legacy.tick(s);s.version=X.VERSION;s.v52.lastRun={day:s.dayIndex,date:s.date,systems:s.v5.lastRun?.systems?.filter(id=>id.startsWith("v52."))||[]};evaluateAlerts(s);return result}
  function militaryOperationAction(s,domain,action,warId=null,formationId=null){migrate(s);const c=country(s),mil=c.v52.military,war=(s.wars||[]).find(w=>w.id===warId&&!w.ended);if(!["ground","air","naval"].includes(domain))return fail("Dominio operativo no válido.");if(domain==="ground"){if(!X.groundFactors.includes(action))return fail("Factor terrestre no válido.");const current=mil.command.ground[action];mil.command.ground[action]=typeof current==="boolean"?!current:V.round(V.clamp(Number(current)+8,0,100));if(["artillery","electronicWarfare","drones","airSupport"].includes(action)){mil.supply.stocks.ammunition=V.round(Math.max(0,mil.supply.stocks.ammunition-2));mil.supply.stocks.fuel=V.round(Math.max(0,mil.supply.stocks.fuel-1))}}
    else{const catalog=domain==="air"?X.airOperations:X.navalOperations;if(!catalog.includes(action))return fail("Operación no válida.");const op=mil.command[domain][action];op.active=!op.active;op.effect=V.round(V.clamp((op.effect||0)+(op.active?10:-5),0,100));if(domain==="air"){op.sorties=(op.sorties||0)+(op.active?4:0);mil.supply.stocks.fuel=V.round(Math.max(0,mil.supply.stocks.fuel-2.5))}else mil.supply.stocks.fuel=V.round(Math.max(0,mil.supply.stocks.fuel-1.5))}
    const f=formationId&&mil.formations.find(x=>x.id===formationId);if(f)f.orders.push({day:s.dayIndex,domain,action,warId});if(war){war.v52||={engagements:[]};war.v52.lastOrder={day:s.dayIndex,countryId:c.id,domain,action}}return ok(`${domain}: ${action} actualizado; consumo y efectos se resolverán diariamente.`)}
  function postwarAction(s,caseId,option){migrate(s);const item=s.v52.postwarCases.find(x=>x.id===caseId),c=country(s);if(!item||item.occupierId!==c.id)return fail("Expediente de posguerra no encontrado.");if(!X.postwarOptions.includes(option))return fail("Acuerdo no válido.");const target=country(s,item.targetId),war=(s.wars||[]).find(x=>x.id===item.warId);if(option==="annexation"){if(war){war.ended=false;war.settlement={status:"active",resolved:false,type:null,date:null}}if(target){target.occupiedBy=null;target.sovereign=true}const result=legacy.annex(s,item.warId);if(result?.ok===false){if(war)war.ended=true;return result}item.integrationProgress=Math.min(item.integrationProgress,8);item.resistance.nationalIdentity=V.round(V.clamp(item.resistance.nationalIdentity+item.integrationDifficulty*.12,0,100));item.status="contested_integration"}else{item.status="implemented";if(target){target.sovereign=true;target.annexedBy=null;target.occupiedBy=["militaryAdministration","temporaryOccupation","demilitarizedZone"].includes(option)?c.id:null;target.vassalOf=["puppetState","protectorate"].includes(option)?c.id:null;target.postwarStatus=option}if(war){war.ended=true;war.settlement={status:"resolved",resolved:true,type:option,date:s.date}}}item.selectedOption=option;item.decisionDay=s.dayIndex;if(option==="reparations"&&target){const paid=Math.min(target.economy.treasury,item.reparationsDue);target.economy.treasury=V.round(target.economy.treasury-paid);c.economy.treasury=V.round(c.economy.treasury+paid);item.reparationsPaid=paid}if(option==="militaryAdministration"||option==="temporaryOccupation")item.resistance.repression=V.round(V.clamp(item.resistance.repression+10,0,100));return ok(`Acuerdo de posguerra aplicado: ${option}.`)}
  function intelligenceOperation(s,targetId,type,source="humint"){migrate(s);const c=country(s),target=country(s,targetId);if(!target||target.id===c.id||!X.intelligenceOperations.includes(type)||!X.intelligenceSources.includes(source))return fail("Operación o fuente no válida.");const op={id:`intel-${c.id}-${targetId}-${type}-${s.dayIndex}`,type,targetId,source,progress:0,secrecy:75,successChance:V.round(V.clamp(c.v52.intelligence.sources[source].reliability-target.v52.intelligence.counterintelligence*.35,5,92)),status:"active",startedDay:s.dayIndex};c.v52.intelligence.operations.push(op);s.v52.globalIntelOperations.push({...op,ownerId:c.id});return ok(`${type}: operación iniciada contra ${target.name}.`)}
  function technologyAction(s,techId,mode,targetId=null){migrate(s);const c=country(s),k=c.v52.technology.knowledge[techId];if(!k||!X.diffusionModes.includes(mode))return fail("Tecnología o modo de difusión no válido.");k.status=mode;k.diffusion.mode=mode;k.history.push({day:s.dayIndex,mode,targetId});if(mode==="patented")k.patentOwner=c.id;if(mode==="embargoed"&&targetId)k.diffusion.embargoedBy.push(targetId);if(["licensed","exported","diffusing"].includes(mode)&&targetId){k.diffusion.partners.push(targetId);c.v52.technology.transfers.push({techId,mode,targetId,day:s.dayIndex})}return ok(`${k.name}: estado ${mode}.`)}
  function resolveCausalDecision(s,eventId,choice){const ev=s.v52.causalEvents.find(x=>x.id===eventId);if(!ev||ev.status==="resolved")return fail("Crisis no disponible.");const c=country(s,ev.countryId),cost=c.economy.gdp*.002;if(choice==="intervene"&&c.economy.treasury<cost)return fail("Tesorería insuficiente.");if(choice==="intervene"){c.economy.treasury=V.round(c.economy.treasury-cost);c.systems.stability=V.round(V.clamp(c.systems.stability+3,0,100))}if(choice==="reform")c.v5.governance.institutions.stateCapacity=V.round(V.clamp(c.v5.governance.institutions.stateCapacity+2,0,100));ev.status="resolved";ev.resolution={choice,day:s.dayIndex};return ok(`Crisis ${ev.title}: respuesta ${choice}.`)}
  function setAnalysisMap(s,id){if(!X.analysisMaps.includes(id))return fail("Mapa analítico no válido.");country(s).v52.analysis.activeMap=id;return ok(`Mapa ${id} seleccionado.`)}
  function configureAlert(s,metric,operator,threshold,horizon=30){const a=country(s).v52.analysis;if(!metric||![">","<",">=","<="].includes(operator)||!X.riskHorizons.includes(Number(horizon)))return fail("Regla de alerta no válida.");a.alerts.push({id:`alert-${s.dayIndex}-${a.alerts.length}`,metric,operator,threshold:Number(threshold),horizon:Number(horizon),enabled:true,triggered:false});return ok(`Alerta configurada para ${metric}.`)}
  function evaluateAlerts(s){const a=country(s).v52.analysis;for(const rule of a.alerts){const series=a.metricHistory[rule.metric]||[],value=series.at(-1)?.value;if(value==null)continue;rule.lastValue=value;rule.triggered=({">":value>rule.threshold,"<":value<rule.threshold,">=":value>=rule.threshold,"<=":value<=rule.threshold})[rule.operator]}}
  function previewDecision(s,type,intensity=1){const c=country(s),i=V.clamp(Number(intensity)||1,.25,3),before={gdp:c.economy.gdp,inflation:c.economy.inflation,treasury:c.economy.treasury,stability:c.systems.stability,emissions:c.v5.infrastructure.climate.emissions,military:c.v52.military.operationalCapacity.ground};const effects={rate_hike:{gdp:-.002,inflation:-.35,treasury:0,stability:-.2,emissions:-.1,military:0},offensive:{gdp:-.004,inflation:.18,treasury:-c.economy.gdp*.002,stability:-.6,emissions:.4,military:4},reconstruction:{gdp:.006,inflation:.12,treasury:-c.economy.gdp*.003,stability:.8,emissions:.2,military:0},climate_investment:{gdp:.002,inflation:.05,treasury:-c.economy.gdp*.002,stability:.3,emissions:-3,military:0},welfare:{gdp:.003,inflation:.15,treasury:-c.economy.gdp*.002,stability:1.2,emissions:.1,military:0}}[type];if(!effects)return fail("Decisión no reconocida.");const after={...before,gdp:V.round(before.gdp*(1+effects.gdp*i)),inflation:V.round(before.inflation+effects.inflation*i),treasury:V.round(before.treasury+effects.treasury*i),stability:V.round(V.clamp(before.stability+effects.stability*i,0,100)),emissions:V.round(Math.max(0,before.emissions+effects.emissions*i)),military:V.round(V.clamp(before.military+effects.military*i,0,100))};const p={id:`preview-${s.dayIndex}-${c.v52.analysis.decisionPreviews.length}`,type,intensity:i,before,after,causalImpacts:Object.keys(after).map(k=>({metric:k,delta:V.round(after[k]-before[k])})),day:s.dayIndex};c.v52.analysis.decisionPreviews.push(p);return{ok:true,message:`Simulación ${type} creada.`,preview:p}}
  function compareCountries(s,ids){const observer=country(s);const rows=ids.map(id=>country(s,id)).filter(Boolean).map(c=>{if(c.id===observer.id)return{id:c.id,name:c.name,gdp:c.economy.gdp,population:c.economy.population,military:c.v52.military.operationalCapacity.ground,confidence:100};const d=X.ensureDossier(s,observer,c);return{id:c.id,name:c.name,gdp:d.metrics.gdp.estimate,population:d.metrics.population.estimate,military:d.metrics.militaryCapacity.estimate,confidence:d.metrics.gdp.confidence}});observer.v52.analysis.comparisons=rows;return rows}
  function explainMetric(s,label="indicador"){const c=country(s),q=String(label).toLowerCase(),a=c.v52.analysis;let causes=[];if(q.includes("infl"))causes=a.explanations.inflation||[];else if(q.includes("militar")||q.includes("prepar")||q.includes("movilidad"))causes=[{label:"Suministro",impact:V.round(Object.values(c.v52.military.supply.delivered).reduce((x,y)=>x+y,0)/6)},{label:"Mando",impact:V.round(c.v52.military.formations.reduce((x,f)=>x+f.properties.command,0)/Math.max(1,c.v52.military.formations.length))},{label:"Fatiga",impact:-V.round(c.v52.military.formations.reduce((x,f)=>x+f.properties.fatigue,0)/Math.max(1,c.v52.military.formations.length))}];else{const key=Object.keys(a.metricHistory).find(k=>k.toLowerCase().includes(q.replace(/[^a-záéíóúñ]/g,"")))||Object.keys(a.metricHistory)[0],series=a.metricHistory[key]||[],last=series.at(-1),before=series.at(-2);causes=[{label:key||label,impact:last&&before?V.round(last.value-before.value):0},{label:"Horizonte",impact:`día ${s.dayIndex}`}]}return ok(`${label}: ${causes.map(x=>`${x.label} ${typeof x.impact==="number"&&x.impact>=0?"+":""}${x.impact}`).join(" · ")}.`)}
  function annexCountry(s,warId){migrate(s);const war=(s.wars||[]).find(w=>w.id===warId),attacker=country(s,war?.attackerId||war?.attacker||s.controlledCountryId),target=country(s,war?.defenderId||war?.defender),options=E.warSettlementOptions?.(s,warId);if(!war||!attacker||!target||!options?.side)return fail("Guerra o participante no disponible.");if(!options.canAnnexCountry)return fail(`Aún no controlas lo suficiente para imponer la posguerra. Ventaja ${options.advantage||0}.`);const item=X.createPostwarCase(s,war,attacker,target);item.status="pending_settlement";item.selectedOption=null;war.ended=true;war.end=s.date;war.winner=attacker.id;war.loser=target.id;war.result=`Victoria militar sobre ${target.name}`;war.settlement={status:"pending_postwar",resolved:false,type:null,date:s.date};target.occupiedBy=attacker.id;return ok(`Victoria militar sobre ${target.name}. El país permanece separado hasta elegir uno de los 11 regímenes de posguerra.`)}
  Object.assign(E,{createInitialState,hydrateState,tickDay,annexCountry,militaryOperationAction,postwarAction,intelligenceOperation,technologyAction,resolveCausalDecision,setAnalysisMap,configureAlert,previewDecision,compareCountries,explainMetric,version52:true});
  window.NEXUS_V52_BRIDGE={legacy,migrate,militaryOperationAction,postwarAction,intelligenceOperation,technologyAction,resolveCausalDecision,setAnalysisMap,configureAlert,previewDecision,compareCountries,explainMetric,evaluateAlerts};
})();
