"use strict";

window.NEXUS_V52=(()=>{
  const V=window.NEXUS_V5,{clamp,round}=V,VERSION="5.2.0-alpha",SCHEMA=1;
  const echelons=["squad","platoon","company","battalion","brigade","division","corps","army","airWing","flotilla","carrierStrikeGroup"];
  const unitProperties=["personnel","equipment","ammunition","fuel","morale","cohesion","training","experience","readiness","maintenance","fatigue","logistics","command","intelligence","entrenchment","radarSignature","airDefense"];
  const groundFactors=["lineOfSight","terrain","weather","hour","urbanDensity","riverCrossings","mines","fortifications","artillery","electronicWarfare","drones","airSupport","reserves","retreat","encirclement","surrender","guerrilla"];
  const airOperations=["airPatrol","interception","sead","strategicBombing","runwayStrike","aerialRefueling","awacs","drones","cruiseMissiles","aircraftAvailability","flightHours","trainedPilots","spareParts"];
  const navalOperations=["detection","sonar","radar","antiSubmarineWarfare","convoys","blockades","mining","aircraftCarriers","replenishment","landings","straitControl","tradeProtection","portRepair"];
  const supplyTypes=["fuel","ammunition","food","spareParts","replacements","transportCapacity"];
  const postwarOptions=["annexation","puppetState","alliedGovernment","militaryAdministration","demilitarizedZone","protectorate","autonomy","supervisedIndependence","regimeChange","reparations","temporaryOccupation"];
  const resistanceFactors=["occupierLegitimacy","nationalIdentity","religiousDifferences","civilianDamage","repression","collaboration","insurgency","sabotage","terrorism","counterinsurgency","reconstruction","refugeeReturn"];
  const intelligenceSources=["satellites","sigint","humint","cyberEspionage","diplomats","press","trade","militaryReconnaissance","allies"];
  const intelligenceOperations=["technologyTheft","infiltration","sabotage","coup","rebelSupport","disinformation","politicalFunding","electoralInterference","cyberAttack","counterintelligence","networkRemoval"];
  const techDependencies=["basicResearch","appliedResearch","patents","humanCapital","equipment","internationalCooperation","companies","universities","espionage","supplyChain"];
  const diffusionModes=["invented","patented","licensed","copied","stolen","exported","embargoed","diffusing"];
  const techBranches=["quantumComputing","artificialIntelligence","robotics","advancedChips","biotechnology","personalizedMedicine","fusion","smallModularReactors","batteries","carbonCapture","advancedMaterials","hypersonics","missileDefense","electronicWarfare","satellites","additiveManufacturing","precisionAgriculture","desalination","cybersecurity","digitalAdministration"];
  const climateMetrics=["temperature","precipitation","drought","flooding","wildfires","hurricanes","desertification","seaLevel","airQuality","waterAvailability","soilFertility","biodiversityLoss"];
  const analysisMaps=["tradeFlows","electricGrid","logistics","migration","industrialChains","influence","intelligence","pollution","politicalOpinion"];
  const riskHorizons=[30,90,365],reportFrequencies=["weekly","monthly","annual","cabinet"];
  const operationLabels={airPatrol:"Patrulla aérea",interception:"Interceptación",sead:"Supresión de defensas",strategicBombing:"Bombardeo estratégico",runwayStrike:"Ataque a pistas",aerialRefueling:"Reabastecimiento",awacs:"AWACS",drones:"Drones",cruiseMissiles:"Misiles de crucero",detection:"Detección",sonar:"Sonar",radar:"Radar",antiSubmarineWarfare:"Guerra antisubmarina",convoys:"Convoyes",blockades:"Bloqueos",mining:"Minado",aircraftCarriers:"Portaaviones",replenishment:"Reabastecimiento naval",landings:"Desembarcos",straitControl:"Control de estrechos",tradeProtection:"Protección comercial",portRepair:"Reparación en puerto"};
  const personnelFor=e=>({squad:10,platoon:40,company:150,battalion:700,brigade:4200,division:16000,corps:50000,army:120000,airWing:2200,flotilla:1800,carrierStrikeGroup:7500})[e]||1000;
  const echelonFor=u=>{const id=String(u.typeId||"").toLowerCase();if(/carrier/.test(id))return"carrierStrikeGroup";if(/frigate|destroyer|submarine|ship/.test(id))return"flotilla";if(/fighter|bomber|air|helicopter|drone/.test(id))return"airWing";const q=Number(u.quantity)||1;return q>12000?"division":q>2500?"brigade":q>500?"battalion":q>100?"company":"platoon"};
  function seedFormation(c,u,i){const echelon=echelonFor(u),base=clamp(c.militaryReadiness||c.systems.military,20,100),personnel=Math.max(personnelFor(echelon),round((Number(u.quantity)||1)*(echelon==="airWing"?18:echelon==="flotilla"?110:8),0));return{id:`${c.id}-formation-${i+1}`,legacyUnitId:u.id?`${c.id}-legacy-${i+1}`:null,name:u.modelName||u.displayName||u.name||`${c.name} ${echelon} ${i+1}`,echelon,domain:echelon==="airWing"?"air":echelon==="flotilla"||echelon==="carrierStrikeGroup"?"naval":"ground",regionId:u.regionId||null,properties:{personnel,equipment:round(base),ammunition:90,fuel:88,morale:75,cohesion:72,training:round(base*.82),experience:round(Number(u.experience)||35),readiness:round(base),maintenance:78,fatigue:5,logistics:round(c.systems.logistics),command:round((c.systems.intelligence+c.systems.military)/2),intelligence:round(c.systems.intelligence),entrenchment:10,radarSignature:55,airDefense:round(c.systems.technology*.55)},dailyConsumption:{fuel:round(personnel*.000025),ammunition:round(personnel*.000018),food:round(personnel*.000003),spareParts:round(personnel*.000006),replacements:round(personnel*.000001),transportCapacity:round(personnel*.000012)},mobility:base,fireRate:base,supplyStatus:"supplied",orders:[],status:"ready"}}
  function estimate(real,quality,source,day,seed){const uncertainty=clamp(42-quality*.34,3,38),bias=(V.randomFrom(seed)()-.5)*uncertainty*.7,value=round(real*(1+bias/100));return{realValue:real,estimate:value,confidenceInterval:[round(value*(1-uncertainty/100)),round(value*(1+uncertainty/100))],confidence:round(100-uncertainty),ageDays:0,observedDay:day,source,possibleDisinformation:quality<45}}
  function ensureDossier(state,observer,target){observer.v52.intelligence.dossiers||={};if(observer.v52.intelligence.dossiers[target.id])return observer.v52.intelligence.dossiers[target.id];const q=clamp(observer.systems.intelligence,10,98),src=intelligenceSources[Math.abs(V.stableHash(observer.id+target.id))%intelligenceSources.length],metrics={gdp:estimate(target.economy.gdp,q,src,state.dayIndex,`${observer.id}-${target.id}-gdp`),population:estimate(target.economy.population,q,src,state.dayIndex,`${observer.id}-${target.id}-pop`),militaryCapacity:estimate(target.systems.military,q,src,state.dayIndex,`${observer.id}-${target.id}-mil`),readiness:estimate(target.militaryReadiness||target.systems.military,q,src,state.dayIndex,`${observer.id}-${target.id}-ready`),technology:estimate(target.systems.technology,q,src,state.dayIndex,`${observer.id}-${target.id}-tech`),reserves:estimate(target.v5?.economy?.currency?.reserves||0,q,src,state.dayIndex,`${observer.id}-${target.id}-res`)};return observer.v52.intelligence.dossiers[target.id]={targetId:target.id,metrics,lastUpdated:state.dayIndex,sources:[src],deceptionRisk:round(clamp((target.v5?.intelligence?.deception||20)-q*.2,0,100))}}
  function seedKnowledge(c,state){const old=(state.techCatalog||window.NEXUS_CATALOG?.technologies||[]).map(t=>({id:t.id,name:t.name||t.id,legacy:true})),extra=techBranches.map(id=>({id,name:id,legacy:false}));return Object.fromEntries([...old,...extra].map((t,i)=>[t.id,{id:t.id,name:t.name,status:(c.completedTechs||[]).includes(t.id)?"invented":i%7===0?"diffusing":"researched",level:round(clamp(c.systems.technology+(i%5-2)*3,5,120)),progress:round((i*13+c.systems.technology)%100),dependencies:Object.fromEntries(techDependencies.map((d,j)=>[d,round(clamp(c.systems.technology+(j%4-2)*5,5,100))])),diffusion:{mode:i%7===0?"licensed":"domestic",rate:round(clamp(c.systems.technology*.55,5,90)),partners:[],embargoedBy:[]},patentOwner:i%3===0?c.id:null,history:[]}]))}
  function ensureCountry(c,state){c.v52||={};if(!c.v52.military){const legacy=(c.units||[]).filter(u=>(Number(u.quantity)||0)>0).slice(0,18),formations=legacy.map((u,i)=>seedFormation(c,u,i));if(!formations.length)formations.push(seedFormation(c,{name:`Fuerza territorial de ${c.name}`,quantity:500,regionId:null},0));c.v52.military={formations,command:{ground:Object.fromEntries(groundFactors.map((x,i)=>[x,round(45+(i%6)*6)])),air:Object.fromEntries(airOperations.map((x,i)=>[x,{capability:round(clamp(c.systems.technology+(i%5-2)*5,5,100)),active:false,sorties:0,effect:0}])),naval:Object.fromEntries(navalOperations.map((x,i)=>[x,{capability:round(clamp((c.systems.military+c.systems.logistics)/2+(i%5-2)*5,5,100)),active:false,effect:0}]))},supply:{stocks:{fuel:100,ammunition:100,food:100,spareParts:100,replacements:100,transportCapacity:100},dailyDemand:Object.fromEntries(supplyTypes.map(x=>[x,0])),delivered:Object.fromEntries(supplyTypes.map(x=>[x,100])),throughput:round(c.systems.logistics),depots:[],routes:[],convoys:[]},operationalCapacity:{ground:0,air:0,naval:0},battleLog:[]}}
    if(!c.v52.intelligence)c.v52.intelligence={sources:Object.fromEntries(intelligenceSources.map((id,i)=>[id,{id,coverage:round(clamp(c.systems.intelligence+(i%4-2)*7,5,100)),reliability:round(clamp(48+c.systems.intelligence*.45-(i%3)*5,10,98)),compromised:false}])),dossiers:{},operations:[],counterintelligence:round(c.systems.intelligence),networks:[],estimatesUpdated:0};
    if(!c.v52.technology)c.v52.technology={knowledge:seedKnowledge(c,state),portfolio:Object.fromEntries(techDependencies.map((x,i)=>[x,round(clamp(c.systems.technology+(i%5-2)*4,5,100))])),licenses:[],embargoes:[],transfers:[],innovationRate:round(c.systems.technology/10),diffusionRate:round(c.systems.technology*.55)};
    if(!c.v52.climate)c.v52.climate={metrics:{temperature:round(12+(Math.abs(V.stableHash(c.id))%180)/10),precipitation:round(350+(Math.abs(V.stableHash(c.name))%1300)),drought:round(c.v5.infrastructure.climate.waterRisk*.7),flooding:round(c.v5.infrastructure.climate.waterRisk*.45),wildfires:round(c.v5.infrastructure.climate.heatRisk*.55),hurricanes:round(c.map?.coastal?12:2),desertification:round(c.v5.infrastructure.climate.heatRisk*.4),seaLevel:3.7,airQuality:round(clamp(100-c.v5.infrastructure.climate.emissions/Math.max(1,c.economy.gdp)*50,5,100)),waterAvailability:round(clamp(100-c.v5.infrastructure.climate.waterRisk,5,100)),soilFertility:round(clamp(c.systems.food,10,100)),biodiversityLoss:22},resources:{renewableWater:round(c.economy.population*2),arableLand:round(c.economy.population*.18),forestCover:30,mineralPressure:20},disasters:[],causalImpacts:[]};
    c.v52.analysis||={metricHistory:{},explanations:{},alerts:[],risks:{30:[],90:[],365:[]},decisionPreviews:[],reports:[],journal:[],activeMap:"tradeFlows",comparisons:[]};
  }
  function createPostwarCase(state,war,occupier,target){state.v52.postwarCases||=[];let existing=state.v52.postwarCases.find(x=>x.targetId===target.id&&x.status!=="closed");if(existing)return existing;const sizePenalty=round(clamp(target.economy.population/Math.max(.1,occupier.economy.population)*45+target.economy.gdp/Math.max(1,occupier.economy.gdp)*35,0,100));existing={id:`postwar-${war?.id||target.id}-${state.dayIndex}`,warId:war?.id||null,occupierId:occupier.id,targetId:target.id,status:"pending_settlement",selectedOption:null,options:[...postwarOptions],integrationDifficulty:round(clamp(sizePenalty+(100-occupier.v5.governance.institutions.stateCapacity)*.25,5,100)),integrationProgress:0,resistance:{occupierLegitimacy:20,nationalIdentity:80,religiousDifferences:25,civilianDamage:35,repression:10,collaboration:18,insurgency:25,sabotage:18,terrorism:8,counterinsurgency:20,reconstruction:10,refugeeReturn:5},reparationsDue:round(target.economy.gdp*.04),occupationCost:round(target.economy.gdp*.006),startedDay:state.dayIndex};state.v52.postwarCases.push(existing);return existing}
  function ensureWorld(state){state.v52||={schema:0,migrations:[],errors:[],audit:[]};state.v52.postwarCases||=[];state.v52.operationalBattles||=[];state.v52.causalEvents||=[];state.v52.globalIntelOperations||=[];state.v52.technologyMarket||=[];state.v52.analysisMaps??=Object.fromEntries(analysisMaps.map(id=>[id,{id,nodes:[],edges:[],updatedDay:state.dayIndex}]));for(const c of state.countries)ensureCountry(c,state);const player=state.countries.find(c=>c.id===state.controlledCountryId)||state.countries[0];for(const target of state.countries)if(target.id!==player.id)ensureDossier(state,player,target);for(const observer of state.countries){const targets=state.countries.filter(x=>x.id!==observer.id).sort((a,b)=>b.economy.gdp-a.economy.gdp).slice(0,6);for(const target of targets)ensureDossier(state,observer,target)}state.v52.catalogs={echelons,unitProperties,groundFactors,airOperations,navalOperations,supplyTypes,postwarOptions,resistanceFactors,intelligenceSources,intelligenceOperations,techDependencies,diffusionModes,techBranches,climateMetrics,analysisMaps,riskHorizons,reportFrequencies};if((Number(state.v52.schema)||0)<SCHEMA)state.v52.migrations.push({from:Number(state.v52.schema)||0,to:SCHEMA,date:state.date});state.v52.schema=SCHEMA;state.version=VERSION;return state}
  return{VERSION,SCHEMA,echelons,unitProperties,groundFactors,airOperations,navalOperations,supplyTypes,postwarOptions,resistanceFactors,intelligenceSources,intelligenceOperations,techDependencies,diffusionModes,techBranches,climateMetrics,analysisMaps,riskHorizons,reportFrequencies,operationLabels,ensureCountry,ensureDossier,createPostwarCase,ensureWorld,clamp,round};
})();
