"use strict";

(() => {
  const X=window.NEXUS_V51,E=window.NEXUS_ECONOMY,V=window.NEXUS_V5;
  if(!X||!E)throw new Error("v5.1 requiere los motores v5");
  if(E.version51)return;
  const legacy={create:E.createInitialState,hydrate:E.hydrateState,tick:E.tickDay,annex:E.annexCountry,integrate:E.integrateAnnexation};
  const migrate=state=>{if(state.v51?.schema===X.SCHEMA){state.version=X.VERSION;return state}return X.ensureWorld(state)};
  function createInitialState(){const state=legacy.create();migrate(state);E.pushEvent?.(state,"system","Strategic Command v5.1 · Economía y sociedad sistémicas","21 mercados, cuentas nacionales, banca, empresas, logística, energía, demografía, instituciones, medios, crimen y diplomacia multinivel activados.");return state}
  function hydrateState(state){return migrate(legacy.hydrate(state))}
  function tickDay(state){migrate(state);const summary=legacy.tick(state);state.version=X.VERSION;state.v51.lastRun={day:state.dayIndex,date:state.date,systems:state.v5.lastRun?.systems?.filter(id=>id.startsWith("v51."))||[]};return summary}
  function country(state,id=state.controlledCountryId){return E.getCountry(state,id)}
  const ok=message=>({ok:true,message}),fail=message=>({ok:false,message});
  function charge(c,cost){if(c.economy.treasury<cost)return false;c.economy.treasury=V.round(c.economy.treasury-cost);return true}

  function monetaryAction(state,action){const c=country(state),m=c.v5.economy,cb=m.centralBank,cur=m.currency,cost=Math.max(.1,c.economy.gdp*.001);switch(action){
    case"rate_up":cb.policyRate=V.round(V.clamp(cb.policyRate+.5,0,40));break;case"rate_down":cb.policyRate=V.round(V.clamp(cb.policyRate-.5,0,40));break;
    case"qe":if(!charge(c,cost))return fail("Tesorería insuficiente para respaldar el programa.");cb.quantitativeEasing=V.round(cb.quantitativeEasing+cost*5);cur.moneySupply=V.round(cur.moneySupply+cost*5);break;
    case"fx_intervention":if(!charge(c,cost))return fail("No hay tesorería suficiente.");cb.fxIntervention=V.round(cb.fxIntervention+cost);cur.fxIntervention=V.round(cur.fxIntervention+cost);cur.reserves=V.round(Math.max(0,cur.reserves-cost));break;
    case"capital_controls":cur.capitalControls=!cur.capitalControls;cb.capitalControls=cur.capitalControls;break;case"devalue":cur.valuationIndex=V.round(V.clamp(cur.valuationIndex*.9,20,220));cur.rate=V.round(cur.rate*1.1,4);break;case"revalue":cur.valuationIndex=V.round(V.clamp(cur.valuationIndex*1.08,20,220));cur.rate=V.round(cur.rate/1.08,4);break;
    case"dollarize":cur.dollarized=true;cur.union="dollarized";cb.policyRate=4;break;case"bank_holiday":cur.bankHoliday=!cur.bankHoliday;for(const b of m.banks)b.liquidity=V.round(V.clamp(b.liquidity+8,0,100));break;case"sovereign_default":m.sovereign.defaulted=true;m.sovereign.creditRating="D";m.sovereign.riskPremium=25;c.economy.debtRatio=V.round(c.economy.debtRatio*.65);c.systems.stability=V.round(V.clamp(c.systems.stability-18,0,100));break;default:return fail("Medida monetaria desconocida.")}
    return ok(`Medida aplicada: ${action}. Sus efectos se transmitirán a precios, crédito y actividad.`)}
  function financialAction(state,action){const c=country(state),m=c.v5.economy;switch(action){case"bank_rescue":{const cost=c.economy.gdp*.008;if(!charge(c,cost))return fail("Tesorería insuficiente para rescatar la banca.");for(const b of m.banks){b.regulatoryCapital=V.round(V.clamp(b.regulatoryCapital+4,0,30));b.liquidity=V.round(V.clamp(b.liquidity+18,0,100));if(b.status!=="operating")b.status="operating"}break}case"deposit_guarantee":m.depositGuarantee=true;break;case"halt_market":m.financialMarkets.nationalIndices.halted=!m.financialMarkets.nationalIndices.halted;break;case"nationalize":m.corporateEvents.push({type:"nationalization",day:state.dayIndex,status:"executed"});break;case"privatize":m.corporateEvents.push({type:"privatization",day:state.dayIndex,status:"executed"});break;default:return fail("Acción financiera desconocida.")}return ok(`Acción financiera ejecutada: ${action}.`)}
  function corporateAction(state,firmId,action){const c=country(state),f=c.v5.economy.firms.find(x=>x.id===firmId);if(!f)return fail("Empresa no encontrada.");const cost=Math.max(.05,f.revenue*.05);if(["build_plant","acquire","joint_venture","new_product"].includes(action)&&f.cash<cost)return fail("La empresa no dispone de caja suficiente.");f.lastDecision=action;if(action==="build_plant"){const p=f.plants[0];f.plants.push({...p,id:`${f.id}-plant-${f.plants.length+1}`,name:`Ampliación ${f.plants.length+1} · ${f.name}`,capacity:V.round(p.capacity*.7),utilization:20,employees:V.round(p.employees*.55,0)});f.cash=V.round(f.cash-cost)}if(action==="close_factory"&&f.plants.length>1)f.plants.pop();if(action==="automate"){f.productivity=V.round(V.clamp(f.productivity+5,0,180));f.employment=V.round(f.employment*.96,0)}if(action==="raise_wages")f.wages=V.round(f.wages*1.04);if(action==="layoffs")f.employment=V.round(f.employment*.92,0);if(action==="issue_shares")f.cash=V.round(f.cash+cost);if(action==="dividends")f.cash=V.round(Math.max(0,f.cash-f.profit*.4));if(action==="relocate")f.logisticsRisk=V.round(V.clamp(f.logisticsRisk-8,0,100));if(action==="change_suppliers")f.supplyChain=[];return ok(`${f.name}: decisión ${action} registrada.`)}
  function chokepointAction(state,id,action){const cp=state.v51.logistics.chokepoints.find(x=>x.id===id);if(!cp)return fail("Punto estratégico no encontrado.");if(action==="close")cp.status="closed";else if(action==="restrict")cp.status="restricted";else if(action==="open")cp.status="open";else if(action==="escort"){cp.warRisk=V.round(V.clamp(cp.warRisk-15,0,100));cp.status="open"}else return fail("Acción logística desconocida.");return ok(`${cp.name}: estado ${cp.status}. Las rutas se recalcularán en el siguiente ciclo.`)}
  function cityAction(state,cityId,action){const c=country(state),city=c.v51.cities.find(x=>x.id===cityId);if(!city)return fail("Ciudad no encontrada.");const cost=c.economy.gdp*.0015;if(!charge(c,cost))return fail("Tesorería insuficiente.");if(action==="public_housing"){city.housingPrice=V.round(city.housingPrice*.96);city.availableLand=V.round(V.clamp(city.availableLand-3,0,100));city.traits.push("publicHousing")}if(action==="rent_control")city.rentControl=!city.rentControl;if(action==="transit"){city.transport=V.round(V.clamp(city.transport+8,0,100));city.congestion=V.round(V.clamp(city.congestion-6,0,100))}if(action==="technology_park"){city.traits.push("technologyPark");city.employment=V.round(V.clamp(city.employment+3,0,100))}if(action==="sez"){city.specialEconomicZone=true;city.employment=V.round(V.clamp(city.employment+4,0,100))}return ok(`Política urbana aplicada en ${city.name}.`)}
  function influenceAction(state,targetId,channelId){const c=country(state),target=country(state,targetId),channel=c.v51.diplomacy.influence[channelId];if(!target||target.id===c.id||!channel)return fail("Objetivo o canal no válido.");const cost=Math.max(.05,c.economy.gdp*.0005);if(!charge(c,cost))return fail("Tesorería insuficiente.");channel.spending=V.round(channel.spending+cost);channel.targets[target.id]=V.round((channel.targets[target.id]||0)+5);const rel=c.v51.diplomacy.relations[target.id];rel.trust=V.round(V.clamp(rel.trust+2,0,100));rel.culturalInfluence=V.round(V.clamp(rel.culturalInfluence+(channelId==="culture"||channelId==="media"?5:1),0,100));return ok(`${channelId}: influencia ampliada en ${target.name}.`)}
  function treatyAction(state,targetId,type){const c=country(state),target=country(state,targetId);if(!target||target.id===c.id||!X.treatyTypes.includes(type))return fail("Tratado no válido.");const treaty={id:`${type}-${c.id}-${target.id}`,type,parties:[c.id,target.id],signedDay:state.dayIndex,status:"active",compliance:75};if(!state.treatyRegistry.some(x=>x.id===treaty.id))state.treatyRegistry.push(treaty);c.v51.diplomacy.treaties.push(treaty.id);target.v51.diplomacy.treaties.push(treaty.id);return ok(`Tratado de ${type} firmado con ${target.name}.`)}
  function annexCountry(state,warId){const war=(state.wars||[]).find(w=>w.id===warId),attacker=country(state,war?.attackerId||war?.attacker||state.controlledCountryId),defender=country(state,war?.defenderId||war?.defender);const before=defender?.sovereign,result=legacy.annex(state,warId);if(result?.ok!==false&&before!==false&&defender?.sovereign===false&&attacker){X.ensureCountry(attacker,state);X.ensureCountry(defender,state);for(const [id,q] of Object.entries(defender.v5.economy.products)){const p=attacker.v5.economy.products[id];if(!p)continue;for(const k of ["production","inventory","intermediateConsumption","householdConsumption","publicConsumption"])p[k]=V.round((p[k]||0)+(q[k]||0)*(k==="production"?.7:1));p.supply=p.production;p.demand=V.round(p.intermediateConsumption+p.householdConsumption+p.publicConsumption)}for(const [id,value] of Object.entries(defender.v51.demography.ageCohorts))attacker.v51.demography.ageCohorts[id]=V.round(attacker.v51.demography.ageCohorts[id]+value);attacker.v51.cities.push(...defender.v51.cities.map(x=>({...x,id:`annex-${defender.id}-${x.id}`,formerCountryId:defender.id})));attacker.v5.economy.banks.push(...defender.v5.economy.banks.map(x=>({...x,id:`annex-${defender.id}-${x.id}`})))}return result}
  Object.assign(E,{createInitialState,hydrateState,tickDay,annexCountry,monetaryAction,financialAction,corporateAction,chokepointAction,cityAction,influenceAction,treatyAction,version51:true});
  window.NEXUS_V51_BRIDGE={legacy,migrate,monetaryAction,financialAction,corporateAction,chokepointAction,cityAction,influenceAction,treatyAction};
})();
