"use strict";

/* Strategic Command v5.1 · Contrato de datos compatible con v5.0. */
window.NEXUS_V51 = (() => {
  const V=window.NEXUS_V5,{clamp,round}=V,VERSION="5.1.0-alpha",SCHEMA=1;
  const products=[
    ["electricity","Electricidad",.055,"MWh"],["oil","Petróleo",.045,"Mt"],["gas","Gas",.035,"bcm"],["coal","Carbón",.018,"Mt"],["uranium","Uranio",.006,"kt"],
    ["steel","Acero",.042,"Mt"],["aluminum","Aluminio",.018,"Mt"],["copper","Cobre",.017,"Mt"],["lithium","Litio",.008,"kt"],["semiconductors","Semiconductores",.045,"mil M€"],
    ["machinery","Maquinaria",.065,"mil M€"],["fertilizers","Fertilizantes",.018,"Mt"],["grains","Cereales",.055,"Mt"],["meat","Carne",.045,"Mt"],["medicines","Medicamentos",.055,"mil M€"],
    ["vehicles","Vehículos",.06,"mil M€"],["consumerGoods","Bienes de consumo",.105,"mil M€"],["housing","Vivienda",.105,"mil M€"],["digitalServices","Servicios digitales",.065,"mil M€"],["transport","Transporte",.07,"mil M€"],["defense","Defensa",.028,"mil M€"]
  ].map(([id,name,weight,unit])=>({id,name,weight,unit}));
  const inflationKeys=["food","energy","housing","industrialGoods","services","core","imported","wage"];
  const cyclePhases=["expansion","overheating","stagnation","recession","depression","recovery","financial_bubble","banking_crisis","sovereign_debt_crisis"];
  const ageCohorts=["0-4","5-14","15-24","25-39","40-54","55-64","65-79","80+"];
  const professions=["unskilled","technicians","engineers","doctors","nurses","teachers","researchers","itSpecialists","militaryOfficers","industrialOperators","agriculturalWorkers","managers"];
  const educationLevels=["primary","secondary","vocational","university","doctorate","businessTraining","professionalReskilling"];
  const energyTechnologies=["nuclear","coal","combinedCycleGas","fuelOil","hydro","pumpedHydro","onshoreWind","offshoreWind","solarPV","solarThermal","geothermal","biomass","batteries","hydrogen","experimentalFusion"];
  const logisticsNodeTypes=["port","airport","railStation","logisticsHub","refinery","oilPipeline","gasPipeline","powerGrid","borderCrossing","maritimeCanal","strait","warehouse","silo","militaryDepot"];
  const chokepoints=[
    ["SUEZ","Canal de Suez",12],["PANAMA","Canal de Panamá",6],["MALACCA","Estrecho de Malaca",24],["HORMUZ","Estrecho de Ormuz",19],["BAB_EL_MANDEB","Bab el-Mandeb",10],["GIBRALTAR","Gibraltar",9],["BOSPHORUS","Bósforo",5],["ENGLISH_CHANNEL","Canal de la Mancha",11],["CAPE_GOOD_HOPE","Cabo de Buena Esperanza",8],["BLACK_SEA","Mar Negro",7],["RED_SEA","Mar Rojo",10],["SOUTH_CHINA_SEA","Mar de China Meridional",22]
  ].map(([id,name,worldFlow])=>({id,name,worldFlow,status:"open",capacity:100,congestion:20,warRisk:5,insurancePremium:1,delayDays:0}));
  const institutionKeys=["headOfState","government","parliament","senate","judiciary","constitutionalCourt","centralBank","armedForces","police","intelligenceServices","regionalGovernments","municipalities","tradeUnions","employerAssociations","churches","media","lobbies","civilOrganizations"];
  const partyAxes=["economic","social","nationalist","centralist","ecologist","authoritarian","globalist","militarist","religious","liberal"];
  const mediaTypes=["television","press","radio","socialNetworks","publicMedia","privateMedia","foreignPlatforms","influencers","bots","propaganda"];
  const crimeKeys=["administrativeCorruption","politicalCorruption","regulatoryCapture","clientelism","oligarchies","moneyLaundering","smuggling","drugTrafficking","armsTrafficking","taxEvasion","taxHavens","mafias","piracy","cybercrime","sanctionsBlackMarket"];
  const treatyTypes=["freeTrade","customsUnion","commonMarket","monetaryUnion","mutualDefense","baseAccess","militaryTransit","nuclearCooperation","intelligenceSharing","extradition","visas","investmentProtection","climateAgreement","sharedWater","fishing","airspace"];
  const organizationDefs=[
    ["UN","ONU","security",true],["UNSC","Consejo de Seguridad","security",true],["NATO","OTAN","defense",true],["EU","Unión Europea","integration",true],["AU","Unión Africana","regional",true],["ASEAN","ASEAN","regional",true],["MERCOSUR","Mercosur","trade",true],["OPEC","OPEP","energy",true],["G7","G7","coordination",false],["G20","G20","coordination",false],["IMF","FMI","finance",true],["WORLD_BANK","Banco Mundial","finance",true],["WTO","OMC","trade",true],["BRICS","BRICS","coordination",false],["ARAB_LEAGUE","Liga Árabe","regional",true]
  ].map(([id,name,type,binding])=>({id,name,type,binding,members:[],votes:[],funds:100,quota:1,obligations:[],sanctions:[],resolutions:[]}));
  const influenceChannels=["aid","investment","infrastructure","armsSales","culture","education","media","debt","technology","militaryBases","intelligence"];
  const financeInstruments=["sovereignBonds","corporateBonds","commodities","currencies","nationalIndices","sovereignFunds","pensionFunds","simulatedETFs","energyFutures","creditDefaultSwaps","interbank","shortSelling"];
  const cityNames={ESP:["Madrid","Barcelona","Valencia","Sevilla","Bilbao"],USA:["Washington D. C.","New York","Los Angeles","Chicago","Houston"],MEX:["Ciudad de México","Monterrey","Guadalajara"],COL:["Bogotá","Medellín","Cali"],MAR:["Rabat","Casablanca","Tánger"],CHN:["Pekín","Shanghái","Shenzhen"],IND:["Nueva Delhi","Mumbai","Bengaluru"],BRA:["Brasilia","São Paulo","Río de Janeiro"]};

  const scaleFor=(c,p)=>Math.max(.01,c.economy.gdp*p.weight);
  function market(c,p,i){
    const base=scaleFor(c,p),resource=(c.systems.energy+c.systems.industry+c.systems.food+c.systems.technology)/400;
    const specialization=(p.id==="grains"||p.id==="meat"||p.id==="fertilizers")?c.systems.food/70:(p.id==="electricity"||["oil","gas","coal","uranium"].includes(p.id))?c.systems.energy/70:(p.id==="semiconductors"||p.id==="digitalServices")?c.systems.technology/70:c.systems.industry/70;
    const production=round(base*clamp(.45+resource*.28+specialization*.32+(i%5)*.025,.25,1.7));
    const intermediateConsumption=round(base*.42),householdConsumption=round(base*.36),publicConsumption=round(base*.12),demand=round(intermediateConsumption+householdConsumption+publicConsumption);
    return{productId:p.id,unit:p.unit,production,inventory:round(production*.16),intermediateConsumption,householdConsumption,publicConsumption,exports:round(Math.max(0,production-demand)*.72),imports:round(Math.max(0,demand-production)*.88),nationalPrice:100,internationalPrice:100,deficitSurplus:round(production-demand),supply:production,demand,price:100,shortage:round(clamp((demand-production)/Math.max(.01,demand)*100,0,100)),trend:0};
  }
  const bank=(c,i)=>{const assets=round(c.economy.gdp*(.23-i*.025));return{id:`${c.id}-bank-${i+1}`,name:`${c.name} Banco ${i+1}`,assets,deposits:round(assets*.67),mortgages:round(assets*.25),businessCredit:round(assets*.24),consumerCredit:round(assets*.12),sovereignBonds:round(assets*.14),nonPerformingLoans:round(clamp(c.economy.unemployment/3,1,18)),regulatoryCapital:12,liquidity:27,sectorExposure:{housing:25,industry:22,services:30,public:14},internationalExposure:round(8+i*5),status:"operating"}};
  const plant=(c,f,i)=>({id:`${f.id}-plant-${i+1}`,name:`Planta ${i+1} · ${f.name}`,city:(cityNames[c.id]||c.v5.society.cities.map(x=>x.name))[i%(cityNames[c.id]?.length||Math.max(1,c.v5.society.cities.length))]||c.capital||c.name,productId:products[(i+Math.abs(V.stableHash(f.id)))%products.length].id,capacity:round(Math.max(.1,f.revenue*.32)),utilization:65,employees:Math.max(40,round(f.employment/Math.max(1,Math.min(2,Math.ceil(f.employment/12000))),0)),wages:100,inventory:12,suppliers:[],customers:[],energyFootprint:round(f.revenue*.08),waterSecurity:75,logisticsAccess:c.systems.logistics,status:"operating"});
  function ensureCountry(c,state){
    const old=c.v5.economy.products||{};c.v5.economy.products=Object.fromEntries(products.map((p,i)=>{const seeded=market(c,p,i),prior=old[p.id]||{},merged={...seeded,...prior};merged.production=prior.production??prior.supply??seeded.production;merged.nationalPrice=prior.nationalPrice??prior.price??seeded.nationalPrice;merged.internationalPrice=prior.internationalPrice??seeded.internationalPrice;merged.intermediateConsumption=prior.intermediateConsumption??seeded.intermediateConsumption;merged.householdConsumption=prior.householdConsumption??seeded.householdConsumption;merged.publicConsumption=prior.publicConsumption??seeded.publicConsumption;merged.demand=round(merged.intermediateConsumption+merged.householdConsumption+merged.publicConsumption);merged.deficitSurplus=prior.deficitSurplus??round(merged.production-merged.demand);merged.supply=merged.production;merged.price=merged.nationalPrice;return[p.id,merged]}));
    const a=c.v5.economy.accounts;a.privateConsumption??=a.consumption;a.publicExpenditure??=a.government;a.grossCapitalFormation??=a.investment;a.netExports??=round(a.exports-a.imports);a.gdpExpenditure=round(a.privateConsumption+a.publicExpenditure+a.grossCapitalFormation+a.netExports);a.gdpBySector??={agriculture:round(c.economy.gdp*.04),industry:round(c.economy.gdp*.24),construction:round(c.economy.gdp*.07),marketServices:round(c.economy.gdp*.48),publicServices:round(c.economy.gdp*.17)};a.grossNationalIncome??=round(c.economy.gdp*1.01);a.householdDisposableIncome??=round(c.economy.gdp*.64);a.nationalSaving??=round(c.economy.gdp*.22);a.totalFactorProductivity??=round((c.systems.technology+c.systems.industry+c.systems.logistics)/3);a.formalEconomy??=round(c.economy.gdp*(1-c.v5.economy.informalShare/100));a.informalEconomy??=round(c.economy.gdp*c.v5.economy.informalShare/100);a.remittancesReceived??=round(c.economy.gdp*.012);a.remittancesSent??=round(c.economy.gdp*.01);a.internationalInvestmentPosition??=round(c.economy.gdp*(c.economy.confidence-55)/180);a.foreignExchangeReserves??=c.v5.economy.currency.reserves;a.currentAccount??=c.economy.tradeBalance;a.capitalAccount??=round(c.economy.gdp*.002);a.financialAccount??=round(-a.currentAccount-a.capitalAccount);
    c.v51||={};c.v51.inflation??=Object.fromEntries(inflationKeys.map((k,i)=>[k,round(clamp(c.economy.inflation+(i-3)*.18,-3,40))]));c.v51.expectations??={households:50,firms:52,banks:50,inflationNextYear:c.economy.inflation,growthNextYear:c.economy.growth};
    const m=c.v5.economy;m.currency.union??="own";m.currency.monetaryUnion=null;m.currency.moneySupply??=round(c.economy.gdp*.85);m.currency.bankReserves??=round(c.economy.gdp*.09);m.currency.reserveRequirement??=10;m.currency.dollarized??=false;m.currency.bankHoliday??=false;m.currency.valuationIndex??=100;m.currency.fxIntervention??=0;
    const cb=m.centralBank;cb.yieldCurve??={"1y":round(cb.policyRate+.2),"2y":round(cb.policyRate+.4),"5y":round(cb.policyRate+.8),"10y":round(cb.policyRate+1.2),"30y":round(cb.policyRate+1.7)};cb.quantitativeEasing??=0;cb.fxIntervention??=0;cb.capitalControls??=false;
    m.sovereign??={defaulted:false,riskPremium:m.markets.riskPremium,creditRating:c.economy.rating||"BBB",bonds:cb.yieldCurve};m.banks??=Array.from({length:3},(_,i)=>bank(c,i));m.financialMarkets??=Object.fromEntries(financeInstruments.map((id,i)=>[id,{id,index:100+i,volume:round(c.economy.gdp*(.02+i*.004)),volatility:round(8+i*.7),halted:false}]));m.corporateEvents??=[];
    for(const [i,f] of m.firms.entries()){f.plants??=[plant(c,f,0)];f.wages??=100;f.inventories??={[f.plants[0].productId]:round(f.revenue*.04)};f.suppliers??=[m.firms[(i+1)%m.firms.length]?.id].filter(Boolean);f.clients??=[m.firms[(i+2)%m.firms.length]?.id].filter(Boolean);f.shareholders??=[{type:f.ownership,share:60},{type:"market",share:40}];f.patents??=Math.max(0,round(f.revenue*c.systems.technology/5000,0));f.quality??=round((c.systems.technology+f.productivity)/2);f.marketShare??=round(100/m.firms.length);f.politicalRisk??=round(100-c.systems.stability);f.logisticsRisk??=round(100-c.systems.logistics);f.energyFootprint??=round(f.revenue*.08);f.headquarters??={fiscal:c.id,operational:c.id};f.subsidiaries??=(i%3===0?[{id:`${f.id}-sub-1`,countryId:state.countries[(Math.abs(V.stableHash(f.id))+1)%state.countries.length].id,ownership:70}]:[]);f.researchCenters??=(c.systems.technology>55?[{id:`${f.id}-rd-1`,countryId:c.id,researchers:round(f.employment*.025,0)}]:[]);f.markets??=[c.id,...f.subsidiaries.map(x=>x.countryId)];f.supplyChain??=[{input:"materials",supplierId:f.suppliers[0]||null,plantId:f.plants[0].id,reliability:round(c.systems.logistics)},{output:f.plants[0].productId,customers:f.clients}];f.strategy??="organic_growth"}
    const energy=c.v5.infrastructure.energy;energy.technologies??=Object.fromEntries(energyTechnologies.map((id,i)=>[id,{id,installedCapacity:round(energy.capacity*(i<6?.07:.04)),availableCapacity:round(energy.capacity*(i<6?.05:.025)),capacityFactor:round(clamp(88-i*3,12,94)),capex:round(1.2+i*.18),opex:round(18+i*2.1),buildYears:round(clamp(1+i*.35,1,12)),lifetime:25+i*2,emissions:["coal","combinedCycleGas","fuelOil"].includes(id)?650-i*30:15,fuelDependency:["nuclear","coal","combinedCycleGas","fuelOil"].includes(id),flexibility:round(clamp(35+i*4,20,100)),technicalRisk:round(clamp(8+i*2,5,55))}]));energy.hourlyDemand??=Array.from({length:24},(_,h)=>round(energy.demand*(.72+Math.sin((h-7)/24*Math.PI*2)*.18)));energy.seasonalPeak??=round(energy.demand*1.18);energy.storage??=round(energy.capacity*.05);energy.interconnections??=[];energy.gridLosses??=6;energy.marginalPrice??=65;energy.frequency??=50;energy.stability??=c.systems.energy;energy.blackouts??=[];energy.market??={longTermContracts:45,dayAheadPrice:65,strategicReserves:60,subsidies:5,carbonTax:35,emissionRights:100,energyPoverty:round(clamp(28-c.economy.gdp/c.economy.population/3,2,35)),externalDependency:round(clamp(65-c.systems.energy*.5,5,85)),securityOfSupply:c.systems.energy};
    const p=c.economy.population,shares=[.055,.115,.135,.225,.21,.115,.105,.04],regionRows=c.v5.society.cities||[];c.v51.demography??={ageCohorts:Object.fromEntries(ageCohorts.map((id,i)=>[id,round(p*shares[i],4)])),sex:{female:round(p*.505,4),male:round(p*.493,4),other:round(p*.002,4)},regions:Object.fromEntries(regionRows.map(x=>[x.name,round(x.population,4)])),education:{primary:24,secondary:34,vocational:14,university:24,doctorate:2,other:2},occupation:Object.fromEntries(professions.map((id,i)=>[id,round(i<2?12:6.33)])),income:{low:30,middle:55,high:15},nationality:{citizen:94,foreign:6},migrationStatus:{native:90,naturalized:4,regular:4,refugee:1,irregular:1},religion:{plural:100},language:{official:88,other:12},settlement:{urban:c.v5.society.urbanization,rural:round(100-c.v5.society.urbanization)},migration:{drivers:{wage:50,unemployment:c.economy.unemployment,security:c.systems.stability,politicalFreedom:c.v5.governance.media.freedom,culturalAffinity:50,language:60,distance:50,familyNetworks:45,policy:50,housing:100-c.v5.society.housing.rentBurden,climate:100-c.v5.infrastructure.climate.heatRisk,war:0},flows:{brainDrain:0,return:0,refugees:0,internallyDisplaced:0,seasonal:0,integration:55,segregation:20,naturalization:0}}};
    c.v51.labor??={professions:Object.fromEntries(professions.map((id,i)=>[id,{workers:round(p*(i<2?.08:.025),4),vacancies:round(p*.001,4),wageIndex:90+i*4,shortage:0}])),education:Object.fromEntries(educationLevels.map((id,i)=>[id,{students:round(p*(.06-i*.006),4),graduatesPerYear:round(p*(.009-i*.0008),4),durationYears:[6,6,2,4,5,1,1][i],capacity:round(clamp(c.v5.society.education.access-i*3,15,99))}])),trainingPipelines:[],semiconductorRequirements:{engineers:80,technicians:75,ultrapureWater:70,stableElectricity:90,specializedMachinery:82,patents:65,chemicalSuppliers:70,logisticsAccess:80}};
    const names=cityNames[c.id]||c.v5.society.cities.map(x=>x.name).slice(0,5);c.v51.cities??=names.map((name,i)=>({id:`${c.id}-urban-${i+1}`,name,population:round(p*(.18-i*.018),4),housingPrice:round(100+i*9),rent:round(100+i*7),availableLand:round(55-i*5),density:round(45+i*8),transport:round(c.systems.logistics-i*2),congestion:round(25+i*8),services:round(c.systems.stability),pollution:round(35+i*4),security:round(c.systems.stability),employment:round(100-c.economy.unemployment),qualityOfLife:round((c.systems.stability+c.systems.health+c.systems.logistics)/3),traits:[i===0?"financialDistrict":"metropolitanExpansion",i===1?"technologyPark":"publicHousing"],tourismSaturation:10,informalSettlements:round(clamp(20-c.systems.stability/6,0,25)),rentControl:false,specialEconomicZone:false}));
    const g=c.v5.governance;c.v51.institutions??=Object.fromEntries(institutionKeys.map((id,i)=>[id,{id,capacity:round(clamp(g.institutions.stateCapacity+(i%5-2)*3,10,98)),independence:round(clamp(g.institutions.ruleOfLaw+(i%4-2)*4,5,98)),legitimacy:round(clamp(c.systems.approval+(i%3-1)*4,5,98)),budget:round(c.economy.gdp*(.001+i*.0002))}]));
    c.v51.parties??=(c.politics.parties||[]).map((party,i)=>({id:party.id,name:party.name,leader:{name:`Líder de ${party.name}`,competence:50+i*3,loyalty:65},axes:Object.fromEntries(partyAxes.map((axis,j)=>[axis,round(clamp(50+(Number(party.axis)||0)*8+(j%3-1)*12,0,100))])),factions:[{id:`${party.id}-pragmatic`,support:58},{id:`${party.id}-ideological`,support:42}],members:round(p*10000*(party.popularity||10)/100),funding:round(c.economy.gdp*(party.popularity||10)/10000),regionalPresence:{national:party.popularity||10},socialBase:["workers","middleClass"],discipline:75,corruptionRisk:15,popularity:party.popularity||10,credibility:60,electoralProgram:[] }));
    c.v51.government??={ministries:["economy","finance","foreignAffairs","defense","interior","health","education","industry","energy","transport","housing","justice"].map((id,i)=>({id,minister:{name:`Ministro/a de ${id}`,competence:55+i%5*5,loyalty:70-i%4*4},budget:round(c.economy.gdp*.008),performance:55})),minorityGovernment:false,investiturePacts:[],blockedLegislation:[],decrees:[],referendums:[],constitutionalReforms:[],confidence:55,crisis:null};
    c.v51.publicOpinion??={segments:{age:{young:50,adult:55,senior:58},region:{national:55},class:{working:50,middle:58,wealthy:62},profession:{public:57,private:54},education:{basic:50,higher:60},nationalIdentity:{state:60,regional:40},ideology:{left:48,center:58,right:52},income:{low:45,middle:58,high:62}}};
    c.v51.media??={outlets:Object.fromEntries(mediaTypes.map((id,i)=>[id,{id,reach:round(clamp(75-i*3,20,95)),credibility:round(clamp(62-i*2,15,90)),bias:{economic:(i%3-1)*25,social:(i%4-2)*15},narrative:"neutral",ownership:i===4?"public":i===6?"foreign":"private"}])),knownByGovernment:100,knownByPublic:70,publicPerception:55,leaks:[],scandals:[],disinformation:15,censorship:round(100-g.media.freedom),coordinatedCampaigns:[],polarization:g.media.polarization,informationFatigue:10,institutionalCredibility:g.media.trust,pressFreedom:g.media.freedom,psychologicalWarfare:0};
    c.v51.crime??=Object.fromEntries(crimeKeys.map((id,i)=>[id,round(clamp(g.corruption.perception*.55+g.crime.organized*.35+(i%4)*2,1,75))]));c.v51.enforcement??={spending:round(c.economy.gdp*.012),incarceration:18,policeAbuseRisk:8,socialTensionCost:4,investigations:[]};
    const rel={};for(const other of state.countries){if(other.id===c.id)continue;const base=c.relations?.[other.id]??50;rel[other.id]={trust:base,ideologicalAffinity:50,economicDependence:round(clamp(Math.abs(c.economy.tradeBalance)/Math.max(1,c.economy.gdp)*100+10,0,100)),historicalRivalry:round(100-base),territorialDisputes:0,militaryCooperation:base>70?55:10,intelligenceSharing:base>75?45:5,culturalInfluence:40,migration:25,energy:25,debt:10,mutualPublicOpinion:base}}
    c.v51.diplomacy??={relations:rel,treaties:[],organizationMemberships:[],influence:Object.fromEntries(influenceChannels.map(id=>[id,{power:round((c.v5.foreign.influence+c.v5.foreign.softPower)/2),spending:round(c.economy.gdp*.001),targets:{}}]))};
  }
  function ensureWorld(state){
    state.v51||={schema:0,migrations:[],audit:[],errors:[]};
    state.v51.logistics??={nodes:[],routes:[],shipments:[],chokepoints:chokepoints.map(x=>({...x})),globalInsuranceIndex:100,globalCongestion:20};
    if(!state.v51.logistics.nodes.length)for(const c of state.countries.filter(x=>x.sovereign!==false))for(let i=0;i<logisticsNodeTypes.length;i++)state.v51.logistics.nodes.push({id:`${c.id}-node-${i+1}`,countryId:c.id,type:logisticsNodeTypes[i],name:`${logisticsNodeTypes[i]} · ${c.name}`,capacity:round(Math.max(1,c.economy.gdp*(.003+i*.00035))),utilization:55,reliability:c.systems.logistics,customsDelay:1,status:"operating"});
    state.v51.organizations??=organizationDefs.map(x=>({...x,members:[],votes:[],obligations:[],sanctions:[],resolutions:[]}));
    const ids=state.countries.map(c=>c.id),members={UNSC:["CHN","FRA","RUS","GBR","USA","ALB","BRA","ECU","GAB","GHA","JPN","MLT","MOZ","CHE","ARE"],NATO:["ALB","BEL","BGR","CAN","HRV","CZE","DNK","EST","FIN","FRA","DEU","GRC","HUN","ISL","ITA","LVA","LTU","LUX","MNE","NLD","MKD","NOR","POL","PRT","ROU","SVK","SVN","ESP","SWE","TUR","GBR","USA"],EU:["AUT","BEL","BGR","HRV","CYP","CZE","DNK","EST","FIN","FRA","DEU","GRC","HUN","IRL","ITA","LVA","LTU","LUX","MLT","NLD","POL","PRT","ROU","SVK","SVN","ESP","SWE"],ASEAN:["BRN","KHM","IDN","LAO","MYS","MMR","PHL","SGP","THA","VNM"],MERCOSUR:["ARG","BRA","PRY","URY","BOL"],OPEC:["DZA","COG","GNQ","GAB","IRN","IRQ","KWT","LBY","NGA","SAU","ARE","VEN"],G7:["CAN","FRA","DEU","ITA","JPN","GBR","USA"],G20:["ARG","AUS","BRA","CAN","CHN","FRA","DEU","IND","IDN","ITA","JPN","MEX","RUS","SAU","ZAF","KOR","TUR","GBR","USA"],BRICS:["BRA","RUS","IND","CHN","ZAF","EGY","ETH","IRN","ARE"],ARAB_LEAGUE:["DZA","BHR","COM","DJI","EGY","IRQ","JOR","KWT","LBN","LBY","MRT","MAR","OMN","PSE","QAT","SAU","SOM","SDN","SYR","TUN","ARE","YEM"]};for(const org of state.v51.organizations){if(org.id==="AU")org.members=state.countries.filter(c=>c.continent==="Africa"||c.region==="Africa").map(c=>c.id);else if(members[org.id])org.members=members[org.id].filter(id=>ids.includes(id))}
    for(const c of state.countries){ensureCountry(c,state);for(const org of state.v51.organizations)if((org.id==="UN"||org.id==="IMF"||org.id==="WORLD_BANK"||org.id==="WTO")&&!org.members.includes(c.id))org.members.push(c.id);c.v51.diplomacy.organizationMemberships=state.v51.organizations.filter(o=>o.members.includes(c.id)).map(o=>o.id)}
    state.v51.catalogs={products:products.map(x=>x.id),inflation:inflationKeys,cycles:cyclePhases,ages:ageCohorts,professions,education:educationLevels,energy:energyTechnologies,logisticsNodes:logisticsNodeTypes,institutions:institutionKeys,partyAxes,media:mediaTypes,crime:crimeKeys,treaties:treatyTypes,organizations:organizationDefs.map(x=>x.id),influence:influenceChannels,finance:financeInstruments};
    if((Number(state.v51.schema)||0)<SCHEMA)state.v51.migrations.push({from:Number(state.v51.schema)||0,to:SCHEMA,date:state.date});state.v51.schema=SCHEMA;state.version=VERSION;return state;
  }
  return{VERSION,SCHEMA,products,inflationKeys,cyclePhases,ageCohorts,professions,educationLevels,energyTechnologies,logisticsNodeTypes,chokepoints,institutionKeys,partyAxes,mediaTypes,crimeKeys,treatyTypes,organizationDefs,influenceChannels,financeInstruments,ensureCountry,ensureWorld,clamp,round};
})();
