"use strict";

(() => {
  const V=window.NEXUS_V5,X=window.NEXUS_V51,{clamp,round}=V;
  const sovereign=s=>s.countries.filter(c=>c.sovereign!==false),avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
  const factor=(c,key,label,impact,detail)=>{c.v5.factors[key]||=[];c.v5.factors[key].push({label,impact:round(impact,3),detail});if(c.v5.factors[key].length>16)c.v5.factors[key].shift()};
  const activeWar=(s,id)=>(s.wars||[]).some(w=>!w.ended&&(w.attacker===id||w.defender===id));

  V.registerSystem({id:"v51.markets.supply-demand",order:22,frequency:"daily",run:({state,rng})=>{
    for(const c of sovereign(state)){const markets=c.v5.economy.products,war=activeWar(state,c.id),logistics=c.v5.infrastructure.logistics,rand=rng(`v51-market:${c.id}`);
      for(const def of X.products){const p=markets[def.id],old=p.nationalPrice,grid=def.id==="electricity"?c.v5.infrastructure.energy.blackoutRisk/100:0,routeCost=(logistics.utilization-70)/500,shock=(war?.012:0)+grid*.018+(rand()-.5)*.0015;
        const productivity=(c.systems.industry+c.systems.technology)/200,popGrowth=Math.max(-.02,c.economy.growth/100);p.production=round(Math.max(.001,p.production*(1+(productivity-.55)/1800-shock/8)),4);p.intermediateConsumption=round(Math.max(0,p.intermediateConsumption*(1+popGrowth/365)),4);p.householdConsumption=round(Math.max(0,p.householdConsumption*(1+(c.economy.population/(c.v51.lastPopulation||c.economy.population)-1)/30)),4);p.publicConsumption=round(Math.max(0,p.publicConsumption*(1+(c.budgets?.welfare||4-4)/20000)),4);p.demand=round(p.intermediateConsumption+p.householdConsumption+p.publicConsumption,4);p.deficitSurplus=round(p.production-p.demand,4);p.imports=round(Math.max(0,-p.deficitSurplus)*clamp(1-routeCost,0,1),4);p.exports=round(Math.max(0,p.deficitSurplus)*clamp(.78-routeCost,0,.9),4);p.inventory=round(clamp(p.inventory+(p.production+p.imports-p.demand-p.exports)/30,0,p.demand*3),4);p.shortage=round(clamp((p.demand-p.production-p.imports-p.inventory*.08)/Math.max(.001,p.demand)*100,0,100));p.internationalPrice=round(clamp(p.internationalPrice*(1+shock+(state.worldIndex.freightIndex-100)/100000),25,800),3);const pressure=p.shortage/800+(p.inventory/Math.max(.001,p.demand)<.08?.002:0)+routeCost/50;p.nationalPrice=round(clamp(p.nationalPrice*(1+pressure+shock*.35-(p.deficitSurplus>0?.0005:0)),20,1000),3);p.trend=round((p.nationalPrice-old)/Math.max(1,old),6);p.supply=p.production;p.price=p.nationalPrice;
      }c.v51.lastPopulation=c.economy.population;
    }
  }});

  V.registerSystem({id:"v51.economy.accounts-inflation-cycle",order:33,frequency:"monthly",run:({state})=>{
    for(const c of sovereign(state)){const a=c.v5.economy.accounts,m=c.v5.economy.products,i=c.v51.inflation,e=c.economy,prices=ids=>avg(ids.map(id=>m[id].trend*1200));
      i.food=round(clamp(i.food*.72+prices(["grains","meat","fertilizers"])*.28,-5,60));i.energy=round(clamp(i.energy*.7+prices(["electricity","oil","gas","coal"])*.3,-5,80));i.housing=round(clamp(i.housing*.75+(c.v5.society.housing.priceIndex-100)/15*.25,-4,50));i.industrialGoods=round(clamp(i.industrialGoods*.75+prices(["steel","aluminum","copper","machinery","vehicles","consumerGoods"])*.25,-5,45));i.services=round(clamp(i.services*.78+(c.v5.society.labor.wageIndex-100)/18*.22,-4,35));i.imported=round(clamp(i.imported*.7+(100-c.v5.economy.currency.valuationIndex)/12+prices(["oil","gas","semiconductors"])*.3,-8,80));i.wage=round(clamp(i.wage*.74+(c.v5.society.labor.wageIndex-100)/12*.26,-4,45));i.core=round(i.industrialGoods*.28+i.services*.47+i.housing*.25);e.inflation=round(i.food*.2+i.energy*.13+i.housing*.2+i.industrialGoods*.16+i.services*.31);
      a.privateConsumption=round(a.realGDP*.58*(1-e.inflation/500));a.publicExpenditure=round(a.realGDP*.2);a.grossCapitalFormation=round(a.realGDP*clamp(.18+c.economy.confidence/1000-c.v5.economy.centralBank.policyRate/1000,.1,.34));a.exports=round(Object.values(m).reduce((s,p)=>s+p.exports,0));a.imports=round(Object.values(m).reduce((s,p)=>s+p.imports,0));a.netExports=round(a.exports-a.imports);a.gdpExpenditure=round(a.privateConsumption+a.publicExpenditure+a.grossCapitalFormation+a.netExports);const sectorTotal=Object.values(a.gdpBySector).reduce((s,v)=>s+v,0)||1;for(const k of Object.keys(a.gdpBySector))a.gdpBySector[k]=round(a.realGDP*a.gdpBySector[k]/sectorTotal);a.grossNationalIncome=round(a.realGDP+(a.remittancesReceived-a.remittancesSent)+(a.internationalInvestmentPosition*.015));a.householdDisposableIncome=round(a.privateConsumption+a.nationalSaving*.45);a.nationalSaving=round(Math.max(0,a.grossNationalIncome-a.privateConsumption-a.publicExpenditure));a.formalEconomy=round(a.realGDP*(1-c.v5.economy.informalShare/100));a.informalEconomy=round(a.realGDP-a.formalEconomy);a.foreignExchangeReserves=c.v5.economy.currency.reserves;a.currentAccount=round(a.netExports+a.remittancesReceived-a.remittancesSent);a.capitalAccount=round(a.realGDP*.002);a.financialAccount=round(-a.currentAccount-a.capitalAccount);a.totalFactorProductivity=round(clamp(a.totalFactorProductivity+(c.systems.technology-50)/1000,10,160));
      const b=c.v5.economy.banking,output=a.outputGap,growth=e.growth,debt=e.debtRatio;let phase=growth>4&&e.inflation>5?"overheating":growth>2.2&&b.stress<45?"expansion":growth<-.8&&growth>-4?"recession":growth<=-4?"depression":Math.abs(growth)<.5?"stagnation":output<0&&growth>0?"recovery":b.stress>75?"banking_crisis":debt>140&&c.v5.economy.markets.riskPremium>7?"sovereign_debt_crisis":c.v5.economy.markets.equityIndex>190?"financial_bubble":"expansion";c.v5.economy.cycle.phase=phase;c.v51.expectations.growthNextYear=round(growth*.65+(c.economy.confidence-50)/12);c.v51.expectations.inflationNextYear=round(e.inflation*.72+(c.v5.economy.centralBank.inflationTarget)*.28);factor(c,"inflation","Componentes emergentes",e.inflation,`Alimentos ${i.food}% · energía ${i.energy}% · vivienda ${i.housing}%`);
    }
  }});

  V.registerSystem({id:"v51.finance.central-bank-banks-markets",order:37,frequency:"monthly",run:({state,rng})=>{
    for(const c of sovereign(state)){const m=c.v5.economy,cb=m.centralBank,cur=m.currency,rand=rng(`v51-finance:${c.id}`),sovereign=m.sovereign;const base=cb.policyRate+sovereign.riskPremium;cb.yieldCurve={"1y":round(base+.1),"2y":round(base+.25),"5y":round(base+.55),"10y":round(base+.95),"30y":round(base+1.45)};sovereign.bonds={...cb.yieldCurve};cur.moneySupply=round(cur.moneySupply*(1+(cb.quantitativeEasing/Math.max(1,c.economy.gdp))/120));cur.bankReserves=round(cur.bankReserves+cb.quantitativeEasing*.08+cb.fxIntervention*.02);cur.valuationIndex=round(clamp(cur.valuationIndex+(c.economy.tradeBalance/Math.max(1,c.economy.gdp))*4-(c.economy.inflation-state.worldIndex.globalInflation)*.04+cb.fxIntervention/Math.max(1,c.economy.gdp)*5,20,220));sovereign.riskPremium=round(clamp(m.markets.riskPremium+(sovereign.defaulted?12:0)+(c.economy.debtRatio-80)/120,0,35));
      for(const b of m.banks){const housingShock=Math.max(0,100-c.v5.society.housing.priceIndex)/25;b.nonPerformingLoans=round(clamp(b.nonPerformingLoans+(c.economy.unemployment-6)*.025+housingShock*.08-(b.regulatoryCapital-10)*.04,0,45));b.liquidity=round(clamp(b.liquidity+(b.deposits*.02-b.nonPerformingLoans*.08)+cb.quantitativeEasing/Math.max(1,m.banks.length),0,100));b.regulatoryCapital=round(clamp(b.regulatoryCapital-b.nonPerformingLoans*.006+(rand()-.5)*.2,0,30));b.status=b.regulatoryCapital<4||b.liquidity<5?"failed":b.nonPerformingLoans>18?"distressed":"operating"}
      m.banking.stress=round(avg(m.banks.map(b=>b.status==="failed"?100:b.status==="distressed"?70:b.nonPerformingLoans*2)));for(const market of Object.values(m.financialMarkets)){market.volatility=round(clamp(market.volatility+m.banking.stress*.01+(rand()-.5)*1.5,2,100));market.index=round(clamp(market.index*(1+(c.economy.growth-cb.policyRate)/1400+(rand()-.5)*market.volatility/5000),5,800));market.halted=market.volatility>82}
    }
  }});

  V.registerSystem({id:"v51.firms.plants-supply-corporate-decisions",order:39,frequency:"monthly",run:({state,rng})=>{
    for(const c of sovereign(state)){const firms=c.v5.economy.firms,markets=c.v5.economy.products,rand=rng(`v51-firms:${c.id}`);for(const f of firms){for(const plant of f.plants){const product=markets[plant.productId],skill=plant.productId==="semiconductors"?c.v51.labor.professions.engineers.workers/Math.max(.001,c.economy.population*.025):1,energy=(100-c.v5.infrastructure.energy.blackoutRisk)/100,logistics=c.systems.logistics/100;plant.utilization=round(clamp(plant.utilization+(product.shortage-15)*.025+(energy+logistics-1.4)*2+(skill-1)*5,5,100));const output=plant.capacity*plant.utilization/100/12;product.production=round(product.production+output*.02);plant.inventory=round(clamp(plant.inventory+output-product.demand/Math.max(1,firms.length)*.02,0,plant.capacity));}
        f.revenue=round(Math.max(.01,f.plants.reduce((s,p)=>s+p.capacity*p.utilization/100,0)*.7));f.profit=round(f.revenue*(.08-c.v5.infrastructure.energy.blackoutRisk/1000-f.logisticsRisk/2000));f.cash=round(Math.max(0,f.cash+f.profit*.55-f.investment));f.health=round(clamp(55+f.profit/Math.max(.1,f.revenue)*250-f.debt/Math.max(.1,f.revenue)*8,0,100));let decision="hold";if(f.health<18)decision="bankruptcy";else if(f.capacity>90&&f.cash>f.revenue*.12)decision="build_plant";else if(f.profit<0)decision=rand()<.5?"close_factory":"layoffs";else if(c.systems.technology>75&&rand()<.18)decision="automate";else if(rand()<.08)decision=["raise_wages","change_suppliers","issue_shares","dividends","joint_venture","vertical_integration","acquire_competitor","relocate","outsource","buyback","new_product"][Math.floor(rand()*11)];f.lastDecision=decision;
        if(decision==="build_plant"&&f.plants.length<5){const base=f.plants[0];f.plants.push({...base,id:`${f.id}-plant-${f.plants.length+1}`,name:`Nueva ${base.name}`,capacity:round(base.capacity*.65),utilization:20,employees:round(base.employees*.55,0)});f.cash=round(f.cash-f.revenue*.1)}if(decision==="automate"){f.productivity=round(clamp(f.productivity+2,0,160));f.employment=round(f.employment*.985,0)}if(decision==="raise_wages")f.wages=round(f.wages*1.02);if(decision==="bankruptcy")mCorporate(c,{type:"bankruptcy",firmId:f.id});
      }}
  }});
  function mCorporate(c,event){const arr=c.v5.economy.corporateEvents;if(!arr.some(x=>x.type===event.type&&x.firmId===event.firmId))arr.push({...event,day:event.day||0,status:"announced"});if(arr.length>50)arr.shift()}

  V.registerSystem({id:"v51.infrastructure.physical-logistics-energy",order:43,frequency:"weekly",run:({state,rng})=>{
    const net=state.v51.logistics,rand=rng("v51-logistics"),closures=net.chokepoints.filter(x=>x.status!=="open");for(const cp of net.chokepoints){cp.congestion=round(clamp(cp.congestion+(state.worldIndex.warRisk/50)+(rand()-.5)*2-(cp.status==="open"?1:0),0,100));cp.insurancePremium=round(1+cp.warRisk*.05+cp.congestion*.025+(cp.status!=="open"?12:0));cp.delayDays=round(cp.status==="closed"?18+cp.congestion/4:cp.congestion/20)}
    for(const node of net.nodes){node.utilization=round(clamp(node.utilization+(rand()-.5)*3+closures.length*.5,10,150));node.reliability=round(clamp(node.reliability-(node.utilization>100?.5:-.08),10,100));node.status=node.reliability<25?"damaged":node.utilization>115?"congested":"operating"}
    net.routes=[];for(const edge of (state.v5Networks.trade.edges||[]).slice(0,500)){const cp=net.chokepoints[Math.abs(V.stableHash(edge.id))%net.chokepoints.length],product=X.products[Math.abs(V.stableHash(edge.from+edge.to))%X.products.length],path=edge.mode==="maritime"?[`${edge.from}-node-12`,`${edge.from}-node-3`,`${edge.from}-node-1`,cp.id,`${edge.to}-node-1`,`${edge.to}-node-4`]:[`${edge.from}-node-12`,`${edge.from}-node-3`,`${edge.from}-node-9`,`${edge.to}-node-9`,`${edge.to}-node-4`];net.routes.push({id:`route-${edge.id}`,from:edge.from,to:edge.to,productId:product.id,path,capacity:round(edge.volume*1.3),transitDays:round(3+cp.delayDays+(edge.mode==="maritime"?12:3)),costPerTon:round(12+cp.insurancePremium*2),congestion:cp.congestion,insurance:cp.insurancePremium,piracyRisk:cp.id==="BAB_EL_MANDEB"?18:3,warRisk:cp.warRisk,weatherRisk:state.worldIndex.climateRisk*.2,blocked:cp.status==="closed",tolls:round(cp.worldFlow*.3),customs:2,sanctions:false,reliability:round(clamp(100-cp.congestion*.4-cp.warRisk*.3,0,100))})}net.shipments=net.routes.slice(0,300).map((r,i)=>({id:`shipment-${r.id}`,routeId:r.id,productId:r.productId,quantity:round(r.capacity*(.35+(i%5)*.1)),origin:r.from,destination:r.to,path:r.path,status:r.blocked?"blocked":"in_transit",transitRemaining:r.transitDays,insured:true}));
    net.globalCongestion=round(avg(net.nodes.map(n=>n.utilization)));net.globalInsuranceIndex=round(avg(net.chokepoints.map(x=>x.insurancePremium))*10);
    for(const c of sovereign(state)){const e=c.v5.infrastructure.energy,tech=Object.values(e.technologies),available=tech.reduce((s,t)=>s+t.installedCapacity*t.capacityFactor/100,0)+e.storage*.25;e.availableGeneration=round(available);e.gridLosses=round(clamp(e.gridLosses+(100-e.gridReliability)*.001,2,18));e.reserveMargin=round((available/e.demand-1)*100);e.marginalPrice=round(clamp(avg([c.v5.economy.products.electricity.nationalPrice,50+e.market.carbonTax*.4]),10,500));e.stability=round(clamp(e.gridReliability-e.blackoutRisk*.25,0,100));e.frequency=round(clamp(50+(e.reserveMargin<0?e.reserveMargin/1000:0),49.5,50.5),3);if(e.blackoutRisk>70&&!e.blackouts.some(x=>state.dayIndex-x.day<30))e.blackouts.push({day:state.dayIndex,durationHours:round(e.blackoutRisk/12),customersAffected:round(c.economy.population*e.blackoutRisk/100)});e.market.dayAheadPrice=e.marginalPrice;e.market.securityOfSupply=round(clamp(100-e.blackoutRisk,0,100));}
  }});

  V.registerSystem({id:"v51.society.demography-migration-labor-education",order:53,frequency:"quarterly",run:({state})=>{
    for(const c of sovereign(state)){const d=c.v51.demography,co=d.ageCohorts,p=c.economy.population,mig=d.migration,war=activeWar(state,c.id);mig.drivers.war=war?90:0;const attraction=(c.economy.growth*3-c.economy.unemployment+(c.systems.stability-50)/3+(c.v5.governance.media.freedom-50)/5-(c.v5.society.housing.rentBurden-25)/3)/1000,net=round(p*clamp(attraction,-.006,.006)/4,5);mig.flows.brainDrain=round(Math.max(0,-net*.35));mig.flows.return=round(Math.max(0,net*.08));mig.flows.refugees=round(war?p*.002:Math.max(0,net*.04));mig.flows.internallyDisplaced=round(war?p*.006:Math.max(0,mig.flows.internallyDisplaced*.92));mig.flows.seasonal=round(p*.0004);mig.flows.naturalization=round(Math.max(0,d.migrationStatus.foreign*.015));mig.flows.integration=round(clamp(mig.flows.integration+(c.budgets.education-4)*.03-mig.flows.segregation*.004,0,100));mig.flows.segregation=round(clamp(mig.flows.segregation+(c.v5.society.housing.rentBurden-25)*.01-(c.budgets.welfare||4)*.02,0,100));
      const birth=co["0-4"]*.012,age=id=>round(co[id]*.0125);co["80+"]=round(Math.max(.001,co["80+"]+age("65-79")*.18-co["80+"]*.025));co["65-79"]=round(Math.max(.001,co["65-79"]+age("55-64")*.45-age("65-79")*.18));co["55-64"]=round(Math.max(.001,co["55-64"]+age("40-54")*.33-age("55-64")*.45));co["40-54"]=round(Math.max(.001,co["40-54"]+age("25-39")*.33-age("40-54")*.33));co["25-39"]=round(Math.max(.001,co["25-39"]+age("15-24")*.38-age("25-39")*.33+net*.6));co["15-24"]=round(Math.max(.001,co["15-24"]+age("5-14")*.45-age("15-24")*.38+net*.2));co["5-14"]=round(Math.max(.001,co["5-14"]+age("0-4")*.5-age("5-14")*.45));co["0-4"]=round(Math.max(.001,co["0-4"]+birth-age("0-4")*.5+net*.2));const total=Object.values(co).reduce((s,v)=>s+v,0),ratio=p/Math.max(.001,total);for(const k of Object.keys(co))co[k]=round(co[k]*ratio,4);
      for(const [id,ed] of Object.entries(c.v51.labor.education)){ed.students=round(Math.max(.001,ed.students*(1+(ed.capacity-50)/10000)),4);const graduates=round(ed.students/Math.max(1,ed.durationYears)*.18,5);ed.graduatesPerYear=graduates;const target=id==="vocational"?"technicians":id==="university"?"engineers":id==="doctorate"?"researchers":id==="professionalReskilling"?"itSpecialists":null;if(target)c.v51.labor.professions[target].workers=round(c.v51.labor.professions[target].workers+graduates*.25,5)}
      for(const prof of Object.values(c.v51.labor.professions)){prof.shortage=round(clamp(prof.vacancies/Math.max(.0001,prof.workers)*100,0,100));prof.wageIndex=round(prof.wageIndex*(1+prof.shortage/10000+c.economy.inflation/1200))}
    }
  }});

  V.registerSystem({id:"v51.society.cities-housing",order:56,frequency:"monthly",run:({state})=>{for(const c of sovereign(state)){for(const city of c.v51.cities){const jobs=c.economy.growth-city.congestion/50,pressure=(city.population/Math.max(.01,city.availableLand))/10+(100-city.transport)/100;city.housingPrice=round(clamp(city.housingPrice*(1+pressure/1200+(c.v5.economy.centralBank.policyRate<3?.001:0)),25,800));city.rent=round(clamp(city.rent*(1+(city.housingPrice/100-1)/1800-(city.rentControl?.002:0)),20,700));city.congestion=round(clamp(city.congestion+(jobs>0?.2:-.1)-city.transport/1000,0,100));city.pollution=round(clamp(city.pollution+c.v5.infrastructure.climate.emissions/Math.max(1,c.economy.gdp)/100-city.transport/1500,0,100));city.qualityOfLife=round(clamp((city.services+city.security+city.employment+city.transport+(100-city.pollution)+(100-city.congestion))/6,0,100));city.informalSettlements=round(clamp(city.informalSettlements+(city.rent-100)/5000-(c.budgets.housing||0)*.03,0,60))}c.v5.society.housing.priceIndex=round(avg(c.v51.cities.map(x=>x.housingPrice)));c.v5.society.housing.rentBurden=round(clamp(avg(c.v51.cities.map(x=>x.rent))/4,8,70))}}});

  V.registerSystem({id:"v51.governance.institutions-parties-media-crime",order:73,frequency:"monthly",run:({state,rng})=>{for(const c of sovereign(state)){const rand=rng(`v51-gov:${c.id}`),g=c.v51.government;for(const inst of Object.values(c.v51.institutions)){inst.capacity=round(clamp(inst.capacity+(c.budgets.administration||2-2)*.02-c.v5.governance.corruption.perception*.003,5,100));inst.legitimacy=round(clamp(inst.legitimacy+(c.systems.approval-inst.legitimacy)*.02,0,100))}for(const party of c.v51.parties){const legacy=c.politics.parties.find(x=>x.id===party.id);party.popularity=legacy?.popularity??party.popularity;party.credibility=round(clamp(party.credibility+(c.economy.growth-1)*.08-(c.economy.inflation-2)*.05-party.corruptionRisk*.01,0,100));party.funding=round(Math.max(0,party.funding*(1+(party.popularity-20)/2000)))}g.confidence=round(clamp(g.confidence+(c.systems.approval-50)*.02-(g.blockedLegislation.length)*.2,0,100));g.minorityGovernment=(c.politics.coalition||[]).length===1&&(c.politics.parties.find(p=>p.id===c.politics.rulingPartyId)?.popularity||0)<50;if(g.confidence<20&&!g.crisis)g.crisis={type:rand()<.5?"confidence_vote":"government_crisis",day:state.dayIndex,status:"pending"};
      const media=c.v51.media;media.publicPerception=round(clamp(media.publicPerception+(c.systems.approval-media.publicPerception)*.08-media.disinformation*.01,0,100));media.informationFatigue=round(clamp(media.informationFatigue+(state.emergentEvents?.length||0)*.002-media.pressFreedom*.001,0,100));media.polarization=round(clamp(media.polarization+media.disinformation*.01-media.institutionalCredibility*.004,0,100));if(rand()<.025)media.leaks.push({day:state.dayIndex,topic:"Contratos públicos",credibility:round(40+rand()*55),status:"published"});
      const crime=c.v51.crime,enf=c.v51.enforcement;for(const key of Object.keys(crime))crime[key]=round(clamp(crime[key]-enf.spending/Math.max(1,c.economy.gdp)*8+(c.v5.economy.informalShare-15)*.01+(rand()-.5)*.4,0,100));enf.incarceration=round(clamp(enf.incarceration+enf.spending/Math.max(1,c.economy.gdp)*.5,0,100));enf.policeAbuseRisk=round(clamp(enf.policeAbuseRisk+enf.incarceration*.004-c.v5.governance.institutions.ruleOfLaw*.003,0,100));enf.socialTensionCost=round(clamp(enf.policeAbuseRisk*.35+enf.incarceration*.12,0,100));c.v5.economy.informalShare=round(clamp(c.v5.economy.informalShare+(crime.taxEvasion-40)*.005,2,60));
    }}});

  V.registerSystem({id:"v51.world.diplomacy-organizations-influence",order:87,frequency:"monthly",run:({state,rng})=>{const countries=sovereign(state),rand=rng("v51-diplomacy");for(const c of countries){for(const other of countries){if(c.id===other.id)continue;const r=c.v51.diplomacy.relations[other.id];if(!r)continue;const legacy=c.relations?.[other.id]??50;r.trust=round(clamp(r.trust+(legacy-r.trust)*.08-r.historicalRivalry*.002+r.culturalInfluence*.001,0,100));r.economicDependence=round(clamp(r.economicDependence+Math.abs(c.economy.tradeBalance)/Math.max(1,c.economy.gdp)*.02,0,100));r.mutualPublicOpinion=round(clamp((r.trust+r.ideologicalAffinity-r.historicalRivalry*.2)/2,0,100))}for(const channel of Object.values(c.v51.diplomacy.influence)){channel.power=round(clamp(channel.power+channel.spending/Math.max(1,c.economy.gdp)*2+(c.v5.foreign.softPower-50)*.002,0,100))}}
    for(const org of state.v51.organizations){org.quota=round(org.members.length?100/org.members.length:0);org.funds=round(Math.max(0,org.funds+org.members.length*.02));const urgent=(state.wars||[]).filter(w=>!w.ended).length+state.v51.logistics.chokepoints.filter(x=>x.status!=="open").length;if(urgent&&rand()<.12){const vote={id:`${org.id}-${state.dayIndex}`,day:state.dayIndex,motion:urgent>4?"Sanciones y alto el fuego":"Fondo de estabilización",yes:round(35+rand()*55),no:0,abstain:0,vetoed:org.id==="UNSC"&&rand()<.28,status:"voting"};vote.no=round((100-vote.yes)*.65);vote.abstain=round(100-vote.yes-vote.no);vote.status=vote.vetoed?"vetoed":vote.yes>50?"adopted":"rejected";org.votes.push(vote);if(vote.status==="adopted")org.resolutions.push(vote)}}
  }});
})();
